### ISSUE TITLE
Login/2019 Season

### ISSUE THREAD

**Issue by troych** [SoMuchForSubtlety/F1viewer#1]
Good Morning ;)

I've been looking into an easy way to watch/stream F1 on my linux machine. Managed to compile this, got it running too.

2 questions: So far I don't see the 2019 FP1, the VOD on f1tv is already there though.

How would I log in? I didn't see any way to actually input my credentials for f1tv. Or am I completely missing something here?

Sorry for the beginner questions. :)

**Comment by SoMuchForSubtlety** [comment]
No problem :)
I'm working on adding the 2019 and any future season, should be done in a few days at most.
You also don't need credentials.

Please tell my if you have any other issues :)

**Comment by troych** [comment]
I see, I'm running this on my NAS which is headless, didn't think I could just play things. ;) Worked now that I've actually forwarded my X session as a test.

The plan was to find a convenient way to stream this to my TV on my local network since the F1 guys can't provide a proper app for TV's. (I can already manually stream when I look for the m3u8 and token while playing in the browser) You mentioned being able to play with VLC in the readme, could you give me a pointer in the right direction there? I think I could make this work with the VLC http output.

**Comment by SoMuchForSubtlety** [comment]
VLC curretly has a bug that makes the audio and video desync by about 10 seconds for most of the m3u8 files, so streaming with VLC is not viable right now.

My program just get's a playable m3u8 URL and either starts playing that directly with MPV or downloads the m3u8 file (to play it with VLC for example). You can see the m3u8 URL if you lanch the program with the flag `-d` and then press `play with MPV` for any VOD.

I'm not familiar with VLC http output, how do you use that to stream to your TV?

If you update the program it should now also load 2019 :)

**Comment by troych** [comment]
Good morning again, to stream manually I go like this:

vlc --intf telnet --telnet-port 55001 --telnet-password pass F1URL,m3u8 --sout '#duplicate{dst=std{access=http,mux=ts,dst=:8080}'

I've tried modifiying main.go, I can launch vlc to watch instead of mpv but I struggle to pass the right options to it.

**Comment by SoMuchForSubtlety** [comment]
Download the latest version, then replace main.go with [this ](https://hastebin.com/sohowufezi.go) and change `"pass"` in line 212 to your password. 

Let me know if it works. if it doesn't work launch the app with the flag `-d`. A debug section should appear. When you press `Play with MPV` the URL will appear in the debug window. Copy that and try if it works if you start the VLC stream manually.

**Comment by troych** [comment]
Sorry for the delay, was a busy week. :)

Just compiled the latest version, loads much faster now. Is it possible that it is broken for some streams? I get 403 errors for all of the full race weekend vod's. 

The vlc streaming works, thanks for the extra option!

**Comment by SoMuchForSubtlety** [comment]
For me full race weekends work, can you give me some examples of VODs not working? How do they behave? Why do you know they are 403ing? 

I'm happy the VLC option works

**Comment by troych** [comment]
Looks like that was something temporary on my end, it's all working again today :) Thanks again for all the help.
