### ISSUE TITLE
[FEATURE] Add support to synchronize multiple streams

### ISSUE THREAD

**Issue by kross123** [SoMuchForSubtlety/f1viewer#105]
**Is your feature request related to a problem? Please describe.**
When opening multiple streams to follow the race, for example the main stream, a driver and the data channel it's difficult to get them all synced so they run at the same race time.

**Describe the solution you'd like**
A possibility to automatically sync the different streams when you have multiple mpv streams open.

**Describe alternatives you've considered**
I've seen a solution like Syncplay (https://syncplay.pl/). 
Or something like this https://github.com/mpv-player/mpv/issues/1272

It this something you can support or make something similair?

**Comment by PeteSeta** [comment]
I don't think this is a F1viewer problem, from the F1TV side the streams start at different times and therefore cannot be synced automatically.

**Comment by SoMuchForSubtlety** [comment]
I can't really do anything about synchronizing videos. If I ever find a way to do it I will add it, but until then you need to do it manually.
