### ISSUE TITLE
Video not play

### ISSUE THREAD

**Issue by Shako131** [SoMuchForSubtlety/f1viewer#109]
I can't play videos, help me.

![Screenshot_1](https://user-images.githubusercontent.com/61947368/95612687-dc185b80-0a74-11eb-9253-156f1c3b9383.png)

**Comment by PeteSeta** [comment]
Is F1TV supported in your region? If not, do you use a VPN?

**Comment by LsHallo** [comment]
See #54 for more info

**Comment by Shako131** [comment]
@PeteSeta I use VPN and creat account.

**Comment by LsHallo** [comment]
But are you subscribed to f1tv pro?

**Comment by Shako131** [comment]
@LsHallo no

**Comment by LsHallo** [comment]
Well then there is your problem

**Comment by Shako131** [comment]
If I subscribe, I will use it normally and I will not use this application anymore.

**Comment by Shako131** [comment]
1 year ago I was using it normally, I neither needed a VPN nor a subscription.

**Comment by LsHallo** [comment]
Yes but since March it requires a subscription since f1 have fixed the loophole in their system.

**Comment by Shako131** [comment]
Then I can no longer understand the duty of this app, why use it?

**Comment by LsHallo** [comment]
It was never designed to circumvent the system. It's to make it easy to play f1tv in different players and with fixed quality using ffmpeg etc. If you just want to watch you don't need to use this app that is correct.

**Comment by LsHallo** [comment]
I personally use it to download all sessions via ffmpeg to save in my plex library.

**Comment by Shako131** [comment]
ok, thank you for helping. close issue.
