### ISSUE TITLE
[FEATURE] Round and start datetime variables for file naming

### ISSUE THREAD

**Issue by notbrain** [SoMuchForSubtlety/f1viewer#114]
**Is your feature request related to a problem? Please describe.**
I like to name my streams using the Round number of the race - for example, Bahrain is Round 15, so I'd put R15 in the filename. I also like to put the datetime of the start of each event, so my scanner can develop an episode number for it. 

**Describe the solution you'd like**
 - `$round` as a variable we can use to feed to custom commands to build the filename.
 - `$eventDateTime` or similar (`$eventDateTimeISO`) to denote the time. Unfortunately there are a million different time formats that people would want to use, so maybe this would also be determined by a formatting string in the config.json. I like to use `YYYY-MM-DD-HHMM` in my filenames, but that's just me. Alternative would be `$eventYear`, `$eventMonth`, `$eventDay`, `$eventHour`, `$eventMinute` to please everyone and let them configure custom commands fully.

**Comment by SoMuchForSubtlety** [comment]
Thank you for the suggestion, I added the new variables `$time` (RFC3339), `$date` (ISO 8601), `$year`, `$month`, `$day`, `$hour`, `$minute` and `$ordinal` in this commit. https://github.com/SoMuchForSubtlety/f1viewer/commit/63f5779bee19a453acd8f5f5ee06fa1d4da2aaed

A few caveats: 
 * The API only has precise times for newer recent, old seasons only have year, day and month.
 * The API does not have a concept or rounds, so we have to rely on the order the API returns events in, or load all events and take a big performance hit. The former approach seems to work fine except for the 2020 season, where the pre-season tests are after the Australian grand prix for some reason. 

You can download the latest version to test here. https://github.com/SoMuchForSubtlety/f1viewer/actions/runs/392595293

**Comment by notbrain** [comment]
@SoMuchForSubtlety Awesome! I'll try it out!

**Comment by SoMuchForSubtlety** [comment]
Included in the latest release https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v1.5.0
