### ISSUE TITLE
[FEATURE] Get Installed VLC Path in Windows from Windows Registry

### ISSUE THREAD

**Issue by eXhumer1** [SoMuchForSubtlety/f1viewer#115]
**Is your feature request related to a problem? Please describe.**
Currently, you have to add supported media players to one of the path in PATH environment variable, however I find this very inconvenient in Windows because applications are usually not added to PATH directories in Windows. Windows has a better solution for this to lookup specific programs thanks to Windows Registry.

**Describe the solution you'd like**
If runtime platform is Windows, query `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VideoLAN\VLC` (if using 64-bit Windows) or `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\VideoLAN\VLC` (if using 32-bit Windows) to check if VLC is installed and the exact path it is installed in. [This](https://pkg.go.dev/golang.org/x/sys/windows/registry#OpenKey) allows to query Windows Registry in Go Lang.

**Describe alternatives you've considered**
None, but if anyone can suggest something better, feel free to contribute.

**Additional context**
None.

**Comment by SoMuchForSubtlety** [comment]
Thank you for the suggestion, this commit adds support to look up the VLC installation location from the registry 7956d08642e2314e8fd0ed8ade37bdcd5c4a0fc9

You can download the latest f1viewer version [here](https://github.com/SoMuchForSubtlety/f1viewer/actions/runs/403056999), please let me know if it works as expected.

**Comment by eXhumer1** [comment]
Hello. Thanks for the new addition! I just tested it and it worked fine. Once again, thank you so much for adding it.

Feel free to close it as you see fit.

**Comment by eXhumer1** [comment]
Just gonna close it myself since it looks like you already added it to main branch.
