### ISSUE TITLE
Export several main feed urls to M3U

### ISSUE THREAD

**Issue by Calprainn** [SoMuchForSubtlety/f1viewer#118]
First of all: thank you Jakob for this great tool! I appreciate your work.

Question: I don't know if my requested feature already exist but is a M3U export with several main feed urls possible?

My use case: I'm watching the F1 streams with the iPlayTV App on a AppleTV. I've created a formel1.m3u file which contains all five url for a weekend:

`#EXTM3U
#EXTINF:-1,F1 1. Training
https://f1tv-cdn-cent-live.formula1.com/ondemand/2cdb/_C_/3/2/wif1210185109/1/clip_2_master.m3u8?nva=1614087322&ttl=86400&cc=DE&token=0331be32e0feee89270cb
#EXTINF:-1,F1 2. Training
https://f1tv-cdn-cent-live.formula1.com/ondemand/07fd/_C_/3/2/wif1211015018/1/clip_2_master.m3u8?nva=1614087208&ttl=86400&cc=DE&token=017c254ad1211822dea77
#EXTINF:-1,F1 3. Training
https://f1tv-cdn-cent-live.formula1.com/ondemand/dc63/_C_/3/2/wif1211194232/1/clip_2_master.m3u8?nva=1614087224&ttl=86400&cc=DE&token=0a98e4ec7b5a1712b0710
#EXTINF:-1,F1 Qualifying
https://f1tv-cdn-cent-live.formula1.com/ondemand/2298/_C_/3/2/wif1212021054/1/clip_2_master.m3u8?nva=1614087246&ttl=86400&cc=DE&token=0441d1882e0b54f1cc5ee
#EXTINF:-1,F1 Rennen
https://f1tv-cdn-cent-live.formula1.com/ondemand/2355/_C_/3/2/wif1213015555/1/clip_2_master.m3u8?nva=1614087262&ttl=86400&cc=DE&token=09925d8273f92fe56190b
`

The file is placed on my web server. In iPlayTV I can access to this file and all five urls will show like channels: "Training 1", "Training 2", "Qualifying" etc. Until now I need to pull the streaming url with f1viewer and copy/paste it in my m3u file. 

Is there (already) a way to create a m3u file like mine with one (or better all five weekend) main feed urls?

**Comment by SoMuchForSubtlety** [comment]
If you are using macOS or Linux you could create these two commands.
```json
"custom_playback_options": [
	{
		"title": "add to playlist",
		"command": [
			"/bin/sh",
			"-c",
			"echo \"#EXTINF:-1, $session\n$url\n\n\" >>playlist.m3u"
		]
	},
	{
		"title": "create new playlist and add",
		"command": [
			"/bin/sh",
			"-c",
			"echo \"#EXTM3U\n#EXTINF:-1,$session\n $url\n\" >playlist.m3u"
		]
	}
]
```

This will create/overwrite `playlist.m3u` if you run `add track to new playlist` and add to it every time to run `add track to playlist`.

You can even add a third command to copy the playlist to your server.

If you are using Windows you will need to change the command to `["cmd", "/C", "\"output goes here\">", "playlist.m3u"]`
