### ISSUE TITLE
m3u8 compatibility

### ISSUE THREAD

**Issue by TiagoJSilva** [SoMuchForSubtlety/F1viewer#12]
First of all, thanks for not being subtle.

The .m3u8 files exported by the Viewer already had problems in VLC, but now they don't work with Kodi, which had been working until now. The error is "404" (according to Kodi log).

I tried adding the extra information that appears on the MPV titlebar/clip-name manually to the end of the URLs on the m3u8 but the response is the same. Can it be included in the .m3u8 somehow?

If not, maybe the next version can stop exporting .m3u8 or warning that compatibility is very limited?

Keep up the good work!

**Comment by SoMuchForSubtlety** [comment]
Yea they changed their infrastructure and tightened security a bit.
I hope I can get a fix for downloaded m3u8 files before sunday but I can't promise anything.

**Comment by TiagoJSilva** [comment]
It would be good, but I'm so happy that you keep not being subtle, so whenever you can, is fine. MPV works, it's just not as relaxing as my couch. Thank you!

**Comment by SoMuchForSubtlety** [comment]
This should be adressed in [v0.7.1](https://github.com/SoMuchForSubtlety/F1viewer/releases/tag/v0.7.1), but I'm not sure you can get it to work in Kodi. 
You will need to set a cookie manually. Read the release description for more details.

**Comment by TiagoJSilva** [comment]
Thank you. I hadn't used a config.json so far, but just created one based on the sample-config.json in the "wiki" but without the custom playback options. How do I get the content of the cookie? (where do I put the $cookie variable?) - I was expecting a text file beside the .m3u8 or something inside the .m3u8 but it's not there.

**Comment by SoMuchForSubtlety** [comment]
`$cookie` is for custom playback options. When you have it in a custom command it will be replaced with the text of the cookie.
If you want to write the cookie to a file i would do this (assuming you use windows):

add the following to your config.json
```
"custom_playback_options": [
    {
        "title": "save cookie",
        "commands": [
            ["cookie.bat", "$cookie", "$file"]
        ],
    },
]
```
then create the file `cookie.bat` in the same folder as F1Viewer and edit it with any text editor.
the contents of `cookies.bat` should be:

```
@echo off
@echo %1> cookie.txt
```


this will download the .m3u8 file and save the cookie in a text file called `cookie.txt`

**Comment by TiagoJSilva** [comment]
OK, I can create a file that works for Kodi (not an .m3u8), but it still takes a bit of fiddling.
This is my config.json
 ```
{
    "preferred_language": "en",
    "check_updates": true,
    "live_retry_timeout": 300,
    "custom_playback_options": [
        {
            "title": "Save cookie",
            "commands": [
                ["cookie.bat", "$cookie", "$file"]
            ],
        },
        {
            "title": "Save strm",
            "commands": [
                ["stream.bat", "$url"]
            ]
        }
    ]
}
```
My `stream.bat` is a duplicate of your `cookies.bat`
```
@echo off
@echo %1> stream.strm
```

Unfortunately, `$url` is getting truncated before writing to `stream.strm` and doesn't have the same information that is being passed to MPV, but I can get the necessary tokens from `cookies.txt` and build the URL manually.

For the default video and audio streams, all that is needed to work in Kodi (or VLC) is an `.strm` file containing the same URL that appears in the MPV title bar.

Thank you for your help.

**Comment by SoMuchForSubtlety** [comment]
Let me know if that's not clear or i can help in any way.

**Comment by TiagoJSilva** [comment]
If you can find out why the exported `$url` is getting truncated three characters after `?` (on the first `=`), creating a valid `.strm` would be automatic. Otherwise, I am fine as it is. I'm OK with "some assembly required".

**Comment by SoMuchForSubtlety** [comment]
Yea the url should not get truncated, that's a bug. I'll take a look.

**Comment by SoMuchForSubtlety** [comment]
The issue seems to be with the batch file, the `&` characters in the URL seem to confuse it. If you want I can write a go program or python script for you to properly write the URL to a file.

**Comment by TiagoJSilva** [comment]
That would be perfect, if it's not too much trouble. Like I said, I'm OK with editing some text files. 
Thankfully the solution was easy this time. Who knows what they're going to close next time?

**Comment by SoMuchForSubtlety** [comment]
I wrote a simple [go program](https://gist.github.com/SoMuchForSubtlety/b77bd3efa180b916b5be4a88fb7f51f6)
it accepts two arguments:

```
  -content string
        what gets written to the file
  -dir string
        the file you want to write to (default "./downloads/stream.strm")
```

your custom command should look like this
```
"commands": [
    ["writetofile.exe", "-content", "$url"]
]
```

You can also change the name of the file like this:

```
"commands": [
    ["writetofile.exe", "-content", "$url", "-dir", "./downloads/filename.whatever"]
]
```

If you click [here](https://github.com/SoMuchForSubtlety/F1viewer/files/3269026/writetofile.zip) you can download it as a 64bit windows executable. Let me know if you need a 32bit version.

**Comment by TiagoJSilva** [comment]
It works perfectly this way. Thank you!

**Comment by SoMuchForSubtlety** [comment]
I can do that for you
