### ISSUE TITLE
[FEATURE] Update to new API

### ISSUE THREAD

**Issue by anthonylavado** [SoMuchForSubtlety/f1viewer#120]
**Is your feature request related to a problem? Please describe.**
As of the end of February 2021, the F1TV website has been redesigned and has a new API that serves video. This new API has all newly added video content, and serves 50fps video when available. The old API currently used should be considered deprecated.

**Describe the solution you'd like**
Update to the new API in order to continue accessing content with the best quality possible.

**Describe alternatives you've considered**
N/A

**Additional context**
It is possible that this will be a larger effort, so I am creating similar issues for all F1TV related repositories. Hopefully there is a way we can all collaborate.

**Comment by anthonylavado** [comment]
Most work seems to be here for now: https://github.com/bbsan2k/plugin.video.f1tv/issues/44

**Comment by LsHallo** [comment]
It seems there might be some interesting urls in this repo: https://github.com/kodosexe/F1Hub

**Comment by mkkrkhm** [comment]
It would be fantastic if @SoMuchForSubtlety might be able to see to this. I've tried some of the alternatives but this project just 'works' ...

**Comment by SoMuchForSubtlety** [comment]
I will publish a new release this week with existing changes and then start working on using the new API. Since other project have already started integrated it I should have a good starting point to work off.

**Comment by mrRichz** [comment]
Will you publish this release with the new API before FP1? :-)

**Comment by SoMuchForSubtlety** [comment]
I'm afraid I'm not that quick.  I will work on it over the next weekend.

**Comment by matthyx** [comment]
Hi, any news?

**Comment by SoMuchForSubtlety** [comment]
This commit https://github.com/SoMuchForSubtlety/f1viewer/commit/b89730413ff60a487a5f24a6638b15b890bc488f adds basic support for the V2 API. 

Sorry it took so long, I had to refactor a bunch of code. V2 API integration is not done yet, this change just lays the groundwork, and some things are broken (see commit message), so I won't create a release yet. If you want to try it you can build the code yourself or download binaries from the [build action](https://github.com/SoMuchForSubtlety/f1viewer/actions/runs/759308586) (only works if you are logged in to GitHub)

**Comment by matthyx** [comment]
Thanks a lot, indeed with the github action artifacts it works for me on ubuntu x86_64.

However I cannot test it on my raspberry pi 4, since when build it I get the error:
`no Go files in...`

**Comment by SoMuchForSubtlety** [comment]
main is now in the `cmd` subfolder, so you have to run `go build -o f1viewer cmd/main.go`

**Comment by ahti** [comment]
The specific build you linked crashed on launch, but the latest build from https://github.com/SoMuchForSubtlety/f1viewer/actions worked nicely with buttery smooth 50fps 👌

Thanks for the update and all the effort you put into this project ❤️

**Comment by SoMuchForSubtlety** [comment]
I just release 2.0, please report any issues or bugs you find.
