### ISSUE TITLE
[BUG] On Mac only QuickTime Player is shown and error on custom playback

### ISSUE THREAD

**Issue by marcvdwalle** [SoMuchForSubtlety/f1viewer#124]
I am using a Macbook. To start a stream I have 2 options: 'Play with QuickTime Player' and 'Copy URL to clipboard'. I have installed VLC and MPV, but both are not showing up. When I add `custom_playback_options` I get an error. There was reported a [similar issue](https://github.com/SoMuchForSubtlety/f1viewer/issues/97), but that was for Windows.

**To Reproduce**
1. Installed f1viewer with Homebrew
2. Installed MPV 0.33.0 (latest) through [here](https://laboratory.stolendata.net/~djinn/mpv_osx/) and moved the .app to Applications folder
3. Changed the `custom_playback_options` option in the config to:
```
"custom_playback_options": [
        {
            "title": "Play with VLC (custom)",
            "command": ["vlc", "$url"]
        },
        {
            "title": "Play with MPV (custom)",
            "command": ["mpv", "$url"]
        }
    ],
```
4. When I launch (in this case MPV) I get the following error: `ERROR: exec: "mpv": executable file not found in $PATH`

**Expected behaviour**
I believe there should be a default 'Play with MPV' option. With the custom options expected behaviour: open selected stream in player that is specified.

**F1TV account plan**
Pro Account, no VPN or proxy.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.2.1
 - Installation method: Homebrew
 - Version: 1.5.0

**Logs**
```
[ERROR] exec: "vlc": executable file not found in $PATH
[ERROR] exec: "mpv": executable file not found in $PATH
```

**Comment by SoMuchForSubtlety** [comment]
The issue is that mpv is not in you `PATH` environment variable, therefore f1viewer does not know where to look for it.

If you install mpv using homebrew it will automatically be added to your path.

You can easily check if an application is in your path by trying to run it from the terminal.

**Comment by marcvdwalle** [comment]
Installing through Homebrew works. Thank you!
