### ISSUE TITLE
Opening videos on 2nd monitor

### ISSUE THREAD

**Issue by jagr200** [SoMuchForSubtlety/f1viewer#125]
Great software. Really appreciate it.

I used the custom commands to open video in"top left" and "bottom right" etc. Is there a way to get it to open on my 2nd monitor? Right now it opens on my monitor 1 and I would like it to open on my monitor 2.

Also are there more areas that can be utilized? Like a 3x3 grid perhaps? Just curious what those would be called. Thanks.

**Comment by RAS915** [comment]
Hi, to your question about opening stream on 2nd monitor. Yesterday I was solving same problem, all streams opened on my main monitor. I figured out that command "--screen=0" will open stream on 2nd monitor. If it doesn't work, try number 1 or 2.

**Comment by jagr200** [comment]
> Hi, to your question about opening stream on 2nd monitor. Yesterday I was solving same problem, all streams opened on my main monitor. I figured out that command "--screen=0" will open stream on 2nd monitor. If it doesn't work, try number 1 or 2.
> 
> Also I created config for Main Feed on main monitor and 9 streams (3x3 grid) on second monitor:
> https://gist.github.com/RAS915/251c1fb2be2ac9a5603238c3db819f6d
> 
> Streams look like this:
> https://i.imgur.com/f8YD6Mo.jpg
> 
> **What you can change to your needs:**
> **"match_title": "xxx"**, // just put name of stream you like to have on this place
> **--volume=xx** // stream volume at start, better set 0 to 3x3 grid
> **--aid=x** // audio track (1=eng, 2=fre, 3=ger, 4=dut, 5=spa, 6=fx, 7=eng)
> **--vid=x** // video quality (1=1920x1080 7015kbps, 2=1280x720 5190 kbps, 3=1024x576 2963 kbps), you will need more bandwidth with 10 opened streams, so set this up according to your internet
> **--screen=x** // monitor select (1=1st monitor, 0=2nd monitor) - keep in mind, this works for me, maybe you need to use 1 and 2
> **--ontop** // good for 3x3 grid, so all streams will be always on top
> 
> **And for exact place on 2nd monitor:**
> --geometry=0:0 = top left
> --geometry=0:50% = middle left
> --geometry=0:100% = bottom left
> --geometry=50%:0 = top middle
> --geometry=50%:50% = middle center
> --geometry=50%:100% = bottom middle
> --geometry=100%:0% = top right
> --geometry=100%:50% = middle right
> --geometry=100%:100% = bottom right
> 
> Hope this helps you. I'm new to F1Viewer, so maybe there is sensible way to create 3x3 config with better commands.



Massive help! This put the feeds on my 2nd screen. Thanks so much!

**Comment by SoMuchForSubtlety** [comment]
###
