### ISSUE TITLE
F1 Viewer - Download Races?

### ISSUE THREAD

**Issue by EmanuelTenorio** [SoMuchForSubtlety/f1viewer#126]
I use the F1 viewer here in Brazil to be able to watch the drive tracker, I don’t have the F1 TV signed because I don’t have a credit card, because of that I can’t access the site and download the races there, is there any way I can download it? Are you currently there with the F1 Viewer? If not, is it something you plan to do in the future?

**Comment by EmanuelTenorio** [comment]
is there any way to download it currently from the f1 viewer?*

**Comment by EmanuelTenorio** [comment]
can you tell me which custom command for this? I really don't understand anything about it: S I tried the one on <> Code but it ended up not working

**Comment by EmanuelTenorio** [comment]
I ended up finding out, thanks!

**Comment by Vallesuski** [comment]
> I ended up finding out, thanks!

Can you please explain how to download races?
