### ISSUE TITLE
60FPS ?

### ISSUE THREAD

**Issue by RomaiinGIT** [SoMuchForSubtlety/f1viewer#127]
Why there is not 60ps ? And only 25fps ?

**Comment by nyebalac** [comment]
I miss this feature so much too

**Comment by jagr200** [comment]
Use race control if you want the updated 60fps. But F1tv viewer is so much better with layouts and settings.

**Comment by RomaiinGIT** [comment]
If 'race control' can do it why f1viewer can't ?

**Comment by jagr200** [comment]
> If 'race control' can do it why f1viewer can't ?

Because Race Control has updated their API where F1Viewer has not. And he has said he isn't working on it too much. Its been 4 weeks since his last update. Don't count on it anytime soon.

**Comment by SoMuchForSubtlety** [comment]
The upgrade to the new API is discussed in #120
