### ISSUE TITLE
403 Forbidden, not showing any videos

### ISSUE THREAD

**Issue by Plebster** [SoMuchForSubtlety/f1viewer#128]
No videos playing for this season or last season... getting a 403 error both in f1viewer and if copying the url to a browser.

example url:
https://f1tv-cdn-cent-live.formula1.com/ondemand/f86b/_C_/3/2/wif0702175553/1/clip_2_master.m3u8?nva=1618647535&ttl=86400&cc=US&token=066f1000d4e26b24d8cf0
(Austrian 2020 FP1)

it also states that YouTube-dl is out of date:

<img width="674" alt="Screenshot 2021-04-17 at 09 22 17" src="https://user-images.githubusercontent.com/26409656/115106772-7d212b00-9f5e-11eb-8ea9-4d078f4e2340.png">

It also does the same for live sessions too.

Looking in the logs it says there is an auth error:
Could not get auth token: The specified item could not be found in the keyring

[2021-04-17.log](https://github.com/SoMuchForSubtlety/f1viewer/files/6328858/2021-04-17.log)

I have also uninstalled and reinstalled via brew and there is no change

As you can see in the logs I have tried to log out and to log back in but this created an error too.

Running on OSX 11.2.3(intel), f1viewer 1.5 was working fine for the last Grand Prix, and all of last season.

cheers,

Jim

**Comment by SoMuchForSubtlety** [comment]
This is an issue with mpv or youtube-dl, not f1viewer. Update mpv and try again. If the issue persists you can reopen this issue.

**Comment by Plebster** [comment]
I have run brew upgrade mpv... now mpv and YouTube-dl is upgraded to the latest version, however I still have a 403 forbidden error in both f1viewer and copying the url into chrome.

<img width="849" alt="Screenshot 2021-04-18 at 10 13 21" src="https://user-images.githubusercontent.com/26409656/115140352-b923c100-a02e-11eb-9a27-cf3998e29abe.png">


[2021-04-18.log](https://github.com/SoMuchForSubtlety/f1viewer/files/6330842/2021-04-18.log)


The log now says it can't find user name in keyring...

I have checked the keychain and the username and password for my f1tv account are there

**Comment by Plebster** [comment]
hey,

I forgot to mention that I use this over a VPN, I usually use a server in the USA, with this I get the 403 error. I have used a server in Switzerland and it works as expected.

Other some other countries seem to work too. Although I haven't tested this extensively. 

Does this help at all?

**Comment by SoMuchForSubtlety** [comment]
I can't really do anything about that I'm afraid. I have no influence over what streams work where.
