### ISSUE TITLE
My player cannot read the m3u8

### ISSUE THREAD

**Issue by Oinie** [SoMuchForSubtlety/F1viewer#13]
I do not know why it no longer works. F1viewer can get the m3u8 file easily but my video player cannot connect to the server of liberty.
 
this happens on pretty much any video in 2019, some in 2018. But for instance the padock pass plays well. I tried on two different computers with different ISPs and I disable the windows  firewall.
this is the data.m3u8 i try to play  

in my player, I paste also the ''FullStreamURL'' of the stream i seek but that fails too. i try one fo the URL written in the m3u8 file directly, and it fails too.

I also try with the MPV player and the data stream is played
 
I also tried on portable vlc, VLCPortable_3.0.7.paf stock settings and it does not work. I can play other m3u8 files non-related to f1  without problem.

**Comment by SoMuchForSubtlety** [comment]
Yea F1TV changed their infrastructure so now you need a cookie to play some videos. Just the downloaded .m3u8 isnt enought anymore.

What player do you use? maybe I can find a solution for you.

**Comment by Oinie** [comment]
okay i jsut saw that
here is my config file

```
{
    "preferred_language": "de",
    "check_updates": true,
    "custom_playback_options": [
        {
            "title": "Play with MPV custom",
            "commands": [
                ["mpv", "$url", "--alang=de"]
            ],
            "watchphrase": "Video",
            "command_to_watch": 0,
        "title": "save cookie",
        "commands": [
            ["cookie.bat", "$cookie", "$file"]
        ]
        }
    ]
}
```

and with the cookie.bat the cookie.txt is created. then i download the m3u8 and I use my player to play ti and it works.

**Comment by SoMuchForSubtlety** [comment]
` ["C:\Program Files (x86)\myplayer.exe", "$url", "--alang=de"]`
The issue is probably the backslashes acting as escape characters. 
Try this instead:
` ["C:\\Program Files (x86)\\myplayer.exe", "$url", "--alang=de"]`

**Comment by Oinie** [comment]
I tried the double slash \\ but the option is not listed (but this time, option ''cookie'' is listed)

├──Main Feed                                                               │                                                                                     ││  │     │  │  ├──save cookie                                                          │                                                                                     ││  │     │  │  ├──Play with MPV                                                        │                                                                                     ││  │     │  │  ├──Download .m3u8                                                       │                                                                                     ││  │     │  │  └──GET URL           

my config:
            "title": "Play with VLC custom",
            "commands": [
                ["D:\\pgm\\VLCPortable\\VLCPortable.exe", "$url", "--alang=de"]
            ],

**Comment by SoMuchForSubtlety** [comment]
Paste your config.json here and see if you get any errors. https://jsonlint.com/

Also try using [this snapshot version of F1Viewer](https://github.com/SoMuchForSubtlety/F1viewer/files/3307301/F1viewer.zip) and tell me what the log.txt says

**Comment by Oinie** [comment]
okay it works now, my error was  that the custom player was nested in the generic MPV command.

THere are 2 problems now:
-first the player loads a video of length 2 minutes or so. i have to change the quality of the video (to anything) to get the 1h long video

the other problem is that there are no sound at all whereas when MPV plays it, the sound is here. Same thing with ''youtube-dl'' option from the stock ''sample-config''


here is my file

```
{
    "preferred_language": "en",
    "check_updates": true,
    "live_retry_timeout": 60,
    "custom_playback_options": [
        {
            "title": "Play with MPV custom",
            "commands": [
                ["mpv", "$url", "--alang=de"]
            ],
            "watchphrase": "Video",
            "command_to_watch": 0
        },
        {
            "title": "download with youtube-dl and play with MPV",
            "concurrent": true,
            "commands": [
                ["youtube-dl", "$url"],
                ["mpv", "$url"]
            ],
            "watchphrase": "100%",
            "command_to_watch": 0
        },
		{
        "title": "save cookie",
        "commands": [
            ["cookie.bat", "$cookie", "$file"]]},
{
            "title": "download with POT-dl and play with MPV",
            "concurrent": false,
            "commands": [
                ["C:\\Program Files (x86)\\PlayerMini.exe", "$url"]
				],
            "watchphrase": "100%",
            "command_to_watch": 0
        }
    ]
}
```

**Comment by SoMuchForSubtlety** [comment]
Incorrect video length and no sound is an issue with the player you use (I assume VLC?) I con't do anything about that.

The default language not working is because F1TV tags the languages incosistently. They use use "de", "ger" and "deu". Try `"preferred_language": "de,ger,deu",`
If it still selects english you can manually change the language by clicking on this in the lower right.
![laguage selector](https://i.imgur.com/386x8rl.png)

To download videos take a look at ffmpeg. It is very powerful and you can select all or just one audio track.
