### ISSUE TITLE
[FEATURE] Bulk download main feeds for races 

### ISSUE THREAD

**Issue by Sloth-on-meth** [SoMuchForSubtlety/f1viewer#132]
**Is your feature request related to a problem? Please describe.**
I manually have to comb through every single season to get the files.

**Describe the solution you'd like**
I'd like to be able to download all races in a season with one action. I want to add all races to my PleX library

**Describe alternatives you've considered**
multi commands, but that didn't work out right

**Additional context**
nah

**Comment by SoMuchForSubtlety** [comment]
I don't plan to add this kind of feature, but you can use f1viewer as a golang library and write an application that bulk downloads videos.
