### ISSUE TITLE
[FEATURE] ARMv7 32bits - Raspberry Pi

### ISSUE THREAD

**Issue by Vallesuski** [SoMuchForSubtlety/f1viewer#133]
I have tried to install F1VIEWER on my Raspberry Pi 4 with the official Raspbian OS through deb file and it didn't work because is not supported for ARMv7 32 bits architecture.

Is there any chance to get a arm32v7 supported?

Regards.

**Comment by RomaiinGIT** [comment]
Good idea !

**Comment by SoMuchForSubtlety** [comment]
I'll see what I can do for the next release, meanwhile you can build it from source yourself. Install the go compiler, clone this repository and then run `go build -o f1viewer cmd/main.go`

**Comment by Herbstein** [comment]
@Vallesuski I built version 1.5.0 of the program for 32-bit ARM. [f1viewer.zip](https://github.com/SoMuchForSubtlety/f1viewer/files/6405061/f1viewer.zip)
This is obviously just a stop-gap, but if my PR is merged it's the only version you'll not get from official channels.

**Comment by Vallesuski** [comment]
Thank you Herbstein.
