### ISSUE TITLE
Use a custom video player and add an option for video quality for MPV

### ISSUE THREAD

**Issue by Oinie** [SoMuchForSubtlety/F1viewer#14]
So now that I can play the m3u8 files, I would like to create an entry in the f1viewer to directly launch the stream in MPV with the quality and audio I like and add an entry for the same quality and audio but with a custom player.

however,  for MPV, I do not know how to select a quality of a stream.

And when i add my custom player, the f1viewer does not load the config.json. [so f1viewer displays the usual options, MPV+m3u8+the new option ''GET URL'', but not the custom options]

here is my config file which fails to load...

```
{
    "preferred_language": "de",
    "check_updates": true,
    "custom_playback_options": [
        {
            "title": "Play with MPV custom",
            "commands": [
                ["mpv", "$url", "--alang=de"]
            ],
            "title": "Play with custom player",
            "commands": [
                ["C:\Program Files (x86)\myplayer.exe", "$url", "--alang=de"]
            ],
            "watchphrase": "Video",
            "command_to_watch": 0,
        "title": "save cookie",
        "commands": [
            ["cookie.bat", "$cookie", "$file"]
        ]
        }
    ]
}
```

also, i need to launch f1viewer with the ''-d'' option (via a shortcut), otherwise if I click directly on the exe, it ignores the config file.

**Comment by SoMuchForSubtlety** [comment]
please use the initial issue https://github.com/SoMuchForSubtlety/F1viewer/issues/13
