### ISSUE TITLE
Livestreams other than World Feed show the same thing

### ISSUE THREAD

**Issue by jlhilgert** [SoMuchForSubtlety/f1viewer#140]
This is FP2 in Portimao and I managed to reproduce this on both Mac and Windows. Livestreams other than World Feed (e.g. Data, Pit Lane, drivers) show Latifi's feed. Is anyone experiencing the same?

**Comment by SkYNewZ** [comment]
Fixed in the commit 43a984d
<img width="346" alt="image" src="https://user-images.githubusercontent.com/26750012/116710239-6ef4f500-a9c9-11eb-8ef2-32679d60d8e5.png">

**Comment by jlhilgert** [comment]
Already pulled the commit. All perspectives besides World Feed show Latifi's feed.

**Comment by SkYNewZ** [comment]
Oh, sorry, in the excitement I didn't even try...

**Comment by jlhilgert** [comment]
Example from tracker perspective:

![Screenshot 2021-04-30 165330](https://user-images.githubusercontent.com/23634831/116712950-a3ba7980-a9d4-11eb-8d2a-e3479f381519.png)

**Comment by jlhilgert** [comment]
> Oh, sorry, in the excitement I didn't even try… You don't like Latifi ? 🙃

Oh I am the biggest Latifi fanboy there is. But even a Nickhead like myself, needs some data once in a while. 😂

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report, that commit fixes the issue.
