### ISSUE TITLE
[BUG] VLC 

### ISSUE THREAD

**Issue by charlesomer** [SoMuchForSubtlety/f1viewer#141]
**Describe the bug**
VLC does not appear as an option. VLC is in path correctly as far as I'm aware.

**To Reproduce**
1. Select stream to play.
2. MPV appears as well as copying URL but VLC is missing.

**Expected behaviour**
VLC should be shown as an option.

**F1TV account plan**
Pro.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Recent binary for v2 api.
 - https://github.com/SoMuchForSubtlety/f1viewer/actions/runs/800793076

**Comment by SoMuchForSubtlety** [comment]
Did VLC work with f1viewer <= v1.5.0?

**Comment by reacap** [comment]
Vlc working fine for me with a new version

Check your %path% for vlc

**Comment by SoMuchForSubtlety** [comment]
f1viewer checks your PATH environment variable and the Windows registry, I just tested both methods, and both worked for me.

You can see your PATH by running `echo %PATH%` in cmd or `echo $Env:PATH` in PowerShell.

You can also check your registry for `SOFTWARE\WOW6432Node\VideoLAN\VLC` or `SOFTWARE\VideoLAN\VLC`.

**Comment by charlesomer** [comment]
Wow I'm so sorry about that! It wasn't in my path after all despite me thinking I had added it 🙄 

Thank you!
