### ISSUE TITLE
[BUG] Live session links only playback the "Starting shortly" ticker

### ISSUE THREAD

**Issue by Herbstein** [SoMuchForSubtlety/f1viewer#142]
**Describe the bug**
Opening the live World Feed link in MPV and QuickTime only shows the red ticker used before the world feed starts. This is the case even as the f1tv website shows the world feed of, in this case, qualifying

**Expected behaviour**
Expected to show world feed when opening link.

**Screenshots**
<img width="2027" alt="image" src="https://user-images.githubusercontent.com/3884484/116785019-a6ca6e00-aa97-11eb-9be5-348511ea464f.png">

**F1TV account plan**
Pro access without any VPN running

**Desktop (please complete the following information):**
 - MACOS
 - Brew
```
❯ f1viewer -v
Version:     2.0.0
Git commit:  f0e3f920f23abb0cc074f87640a29f2d5350dc58
Built:       2021-05-01T12:15:32Z
```

**Comment by bviolier** [comment]
I have the same issue with all feeds with MPV, but Quicktime is working fine for me. Let me know if I can provide any logs or anything.

**Comment by bviolier** [comment]
Note that on MPV it shows these values, maybe that helps.
![image](https://user-images.githubusercontent.com/1247610/116785276-f198b580-aa98-11eb-8fde-d68a3858cc6f.png)

**Comment by gbtec-ext-estebanfernandez** [comment]
Same problem here with MPV. VLC not loading at all.

**Comment by N7Steve** [comment]
Same problem here. VLC not loading at all.

**Comment by Herbstein** [comment]
Can confirm that QuickTime loads the feed properly for me too.

**Comment by ab0mbs** [comment]
Seeing the same issue on Windows 10 as well.

**Comment by rizaon** [comment]
Seems like "--start=0" is being forced in mpv. Custom command without "--start=0" makes it work for me.

**Comment by bviolier** [comment]
Unfortunately, the live session is over and I can't test it anymore, but I am suspecting `--start=0` to be the issue in `mpv`.

**Comment by oopled** [comment]
> Unfortunately, the live session is over and I can't test it anymore, but I am suspecting `--start=0` to be the issue in `mpv`.

Can confirm. Removing '--start=0' fixes the issue

**Comment by SoMuchForSubtlety** [comment]
thanks for the report, I made a new release with the fix https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v2.0.1
