### ISSUE TITLE
[BUG] No error message when using V2 api in unsupported country

### ISSUE THREAD

**Issue by charlesomer** [SoMuchForSubtlety/f1viewer#144]
**Describe the bug**
When using a VPN to a country where F1TV Pro is not supported, no error is provided for the V2 api.

**To Reproduce**
Try to play a stream when in a country where F1TV Pro is not supported.

**Expected behaviour**
V1 of the api displayed a 400 bad request error - something similar.

**F1TV account plan**
Pro

**Desktop (please complete the following information):**
 - OS MacOS
 - installation method Homebrew
 - Version 2.0.0

**Comment by SoMuchForSubtlety** [comment]
When you try to play something, do any error messages appear? Or do you just get an empty URL if you try for example to copy it to your clipboard?

**Comment by charlesomer** [comment]
It looks like the URL is just empty which throws off VLC and QuickTime. I can double check what gets copied later though if need be

**Comment by SoMuchForSubtlety** [comment]
Download the latest build here and see if you get an error message https://github.com/SoMuchForSubtlety/f1viewer/actions/runs/802890651

**Comment by charlesomer** [comment]
Looks like that's done it 👍 Seems to work as expected now 😄
