### ISSUE TITLE
[BUG] Build from source instructions do not work

### ISSUE THREAD

**Issue by choeger** [SoMuchForSubtlety/f1viewer#149]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
I cannot follow the instructions in the README on how to install from source.

**To Reproduce**
1. go get github.com/SoMuchForSubtlety/f1viewer
2. See error

```
** Error **
go get github.com/SoMuchForSubtlety/f1viewer 
go: downloading github.com/SoMuchForSubtlety/golark v1.2.0
go: downloading github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966
go: downloading github.com/rivo/tview v0.0.0-20210312174852-ae9464cc3598
go: downloading github.com/atotto/clipboard v0.1.4
github.com/SoMuchForSubtlety/keyring@v1.1.6: verifying module: checksum mismatch
	downloaded: h1:hD++ioheDXcmCVy+F3MQhyft9FLm0TXGLZ+6xjFN+Cc=
	sum.golang.org: h1:nObpYSKtjp9OfAgT9TGAm23PD886JdH5xtHD+HScZNk=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
go: downloading golang.org/x/sys v0.0.0-20210320140829-1e4c9ba3b0c4
```

**Expected behaviour**
The download and installation should work just fine.

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.

**Comment by SoMuchForSubtlety** [comment]
I corrected the readme, you actually need to run `go get github.com/SoMuchForSubtlety/f1viewer@master`
