### ISSUE TITLE
[BUG] Specified keyring backend not available

### ISSUE THREAD

**Issue by Placemaster** [SoMuchForSubtlety/f1viewer#153]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!![image](https://user-images.githubusercontent.com/987244/117541300-88beb980-b013-11eb-83f2-ac9afcfb5eb1.png)
**Describe the bug**
The Specified keyring backend not available. I need to enter the credentials every time I start F1viewer.
There is no config at $HOME/Library/Application Support/f1viewer

**To Reproduce**
1. Start F1viewer on MacBook Air M1
2. Start logging in with entering credentials
3. Got the error : Specified keyring backend not available

**Expected behaviour**
Not seeing the message. Also should be able to see the the log at  $HOME/Library/Application Support/f1viewer

**Screenshots**

![image](https://user-images.githubusercontent.com/987244/117541300-88beb980-b013-11eb-83f2-ac9afcfb5eb1.png)

**F1TV account plan**
F1 TV pro account
No VPN / proxy

**Desktop (please complete the following information):**
 - MacOS Big Sur 11.3.1
 - manual via brew according to instruction on Github
 - Version:     2.0.1
    Git commit:  f72b2875b558bd696655b6619bb2510e49f1e37a
    Built:       2021-05-01T20:03:48Z

**Logs
[2021-05-08.log](https://github.com/SoMuchForSubtlety/f1viewer/files/6445927/2021-05-08.log)

**Comment by Placemaster** [comment]
Tried all the directions given in #123 but still the keyring is not available. 
Any other options available to solve the issue?

**Comment by Nathaniel-Wu** [comment]
I'm having the same issue on my M1 Mac with the latest v2.1.0 release via Homebrew, my other Intel Mac has no problem though. `go install` or `go get` only gets v1.5.0, had to clone the repo and build from there.
Is this problem unfixable due to some restrictions Apple put on M1 Macs?
