### ISSUE TITLE
[BUG] Linux, no video

### ISSUE THREAD

**Issue by Davincible** [SoMuchForSubtlety/f1viewer#155]
When I select to open in VLC, I only get sound, and a black screen. Running Manjaro Linux 5.12.

![image](https://user-images.githubusercontent.com/25869544/117583579-272c4700-b108-11eb-8adf-d89dde3c2d2d.png)

**Comment by SoMuchForSubtlety** [comment]
I've never had much success with VLC, but others have reported it working. Try using MPV
