### ISSUE TITLE
Hardcoded API key

### ISSUE THREAD

**Issue by Davincible** [SoMuchForSubtlety/f1viewer#156]
https://github.com/SoMuchForSubtlety/f1viewer/blob/96f0d8c788e30ee540527f99d9c0f6a8b25e9ba0/pkg/f1tv/v2/api.go#L22

Noticed you have a hard coded API key. Not sure if this is desired, or just a dummy, but figured I'd mention just to be sure

**Comment by SkYNewZ** [comment]
It's wanted https://github.com/robvdpol/RaceControl/blob/060ab42e138f72941fcd67de973b59060e6bc7b0/RaceControl/Services/RaceControl.Services/F1TV/Constants.cs#L9

They have found a valid API key and use it. The API is not public so this key is not their :wink:
