### ISSUE TITLE
[FEATURE] Using a single subscribed account as a distributor?

### ISSUE THREAD

**Issue by ilovegimi85** [SoMuchForSubtlety/f1viewer#157]
I know fuck all about the inner workings of [REDACTED], but I had a thought in the shower and figured I might as well share it. Could a single subscribed account be used to distribute F1TV to all clients? I'm not saying you make 1 subscribed account and give it to everyone, but rather using that account's info or API or whatever to unlock [REDACTED] for all users?

Tried adding an illustration since I'm worthless at explaining
![mockup](https://user-images.githubusercontent.com/84105239/118050554-c60ea880-b37f-11eb-813b-33ffc249c977.png)

**Comment by hash55** [comment]
so you can share an account with another friend, and pay half of it?
