### ISSUE TITLE
Race spoilers (again)

### ISSUE THREAD

**Issue by peskdale** [SoMuchForSubtlety/F1viewer#16]
Previously addressed in #3, but something is causing them to show up again. WinnerXURL appears in the Info pane when hovering over the name of a Grand Prix under "Full Race Weekends".

(As a side-request, perhaps a config option to just hide the info pane completely? Unless working on code development, it's fairly useless to end users in it's current state.)

**Comment by SoMuchForSubtlety** [comment]
Good point. I'll hide the info pane and only show it in debug mode.

**Comment by SoMuchForSubtlety** [comment]
fixed in https://github.com/SoMuchForSubtlety/F1viewer/commit/b75942f4ad7ec1f3e9099fe87975b93ba1164426
