### ISSUE TITLE
OLD API NOT WORKING ANYMORE?

### ISSUE THREAD

**Issue by hash55** [SoMuchForSubtlety/f1viewer#163]
As the new API does not work well for me, I wonder if it would be possible to get the old api still working. (for versions under **2.0**) 
I know sessions are apparently uploaded in "Full Seasons" section, but when you click it just gets "loading..." and does not show any content. This started to happen just before the Portuguese GP

If  it is not too complicated I would be very pleased if you could upload the new content to 1.9 version, you would do me a favour
Thank you.
![image](https://user-images.githubusercontent.com/84033043/119533648-5be60280-bd86-11eb-8f57-f9c83b7a1508.png)

**Comment by SoMuchForSubtlety** [comment]
Yea, I'm afraid they discontinued it
