### ISSUE TITLE
Status 403 when logging in on MacOS 11.4

### ISSUE THREAD

**Issue by nisargshah95** [SoMuchForSubtlety/f1viewer#167]
I get the following error message when I try to log in on MacOS 11.4. I had tried it once yesterday and it worked fine then.

<img width="882" alt="Screen Shot 2021-06-08 at 3 25 45 PM" src="https://user-images.githubusercontent.com/1448505/121252800-09b8dd00-c86e-11eb-8c07-555054d3af68.png">

f1viewer version:
```
$ f1viewer --version
Version:     2.0.1
Git commit:  f72b2875b558bd696655b6619bb2510e49f1e37a
Built:       2021-05-01T20:03:48Z
```

**Comment by tapessur** [comment]
same problem here!

**Comment by hash55** [comment]
same!

**Comment by NemSim** [comment]
same error for me on Mac OS 11.2.3 (2016 macbook with an intel processor), same f1viewer version

**Comment by Marguelgtz** [comment]
having the same issue

**Comment by soer7022** [comment]
Same here

**Comment by PhillipAlpha** [comment]
I 3 have this issue.

**Comment by sluciow** [comment]
Same issue on Windows 10. Correct credentials but unable to connect.

**Comment by LeJimster** [comment]
Same issue on Linux.  Hope it will be fixed soon as it's the best way I've found to watch f1.

**Comment by pantelisgeor** [comment]
I get the same error on Manjaro

**Comment by Jerek0** [comment]
Same thing on Mac OS 10.14.4

**Comment by disbelieveordoubt** [comment]
Same on Windows 10

**Comment by PRELVAS94** [comment]
Any fix before the Qual?

**Comment by naglis** [comment]
@PRELVAS94 there is a [PR](https://github.com/SoMuchForSubtlety/f1viewer/pull/171) with a quickfix which seems to work.

**Comment by SoMuchForSubtlety** [comment]
sorry for the delay, fixed in the latest release https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v2.1.0
