### ISSUE TITLE
could not authenticate in: got status 403

### ISSUE THREAD

**Issue by camhpj** [SoMuchForSubtlety/f1viewer#169]
Cannot login. Some issue with the http requests and I am not sure what the issue is. To clarify I am on Windows 10 so this is not a complete duplicate of #167 as that user in on Mac.

![403 error](https://user-images.githubusercontent.com/82114003/121556060-8b7d4780-c9e1-11eb-9736-7d65492e0bb9.png)

**Comment by MarcoMeirelles** [comment]
I also got this error

**Comment by madmax76** [comment]
Duplicate with #167 ... please make me mod or someone close this. have the issue too

**Comment by PhillipAlpha** [comment]
I 3 have this problem

**Comment by sluciow** [comment]
Same here. Windows 10. Correct credentials (tested on F1 Site) but not able to connect.

**Comment by Kocicak** [comment]
#171 fixes this issue. Please merge. For those who don't want to wait and enjoy french GP, just download fork from this pull request, go to cmd directory and type `go build` and run the executable.

**Comment by hash55** [comment]
> #171 fixes this issue. Please merge. For those who don't want to wait and enjoy french GP, just download fork from this pull request, go to cmd directory and type `go build` and run the executable.

I completed all you steps and reached the executable file but the 403 error still pops up when trying to log in

**Comment by Kocicak** [comment]
> I completed all you steps and reached the executable file but the 403 error still pops up when trying to log in
I'm sorry to hear that. The exact steps I used are:
```bash
git clone https://github.com/Skinza/f1viewer.git # be sure to use this fork
cd f1viewer/cmd
go build
./cmd #executable file cmd is compiled
```
And it workd. I'm using OpenSUSE Tumbleweed and go 1.16.4

**Comment by ryan13mt** [comment]
@Kocicak would it be a problem if you upload the compiled executable directly please?

**Comment by hash55** [comment]
> > I completed all you steps and reached the executable file but the 403 error still pops up when trying to log in
> 
> I'm sorry to hear that. The exact steps I used are:
> 
> ```shell
> git clone https://github.com/Skinza/f1viewer.git # be sure to use this fork
> cd f1viewer/cmd
> go build
> ./cmd #executable file cmd is compiled
> ```
> 
> And it workd. I'm using OpenSUSE Tumbleweed and go 1.16.4

thanks, now it worked

**Comment by Kocicak** [comment]
> @Kocicak would it be a problem if you upload the compiled executable directly please?

Here it is: https://drive.google.com/file/d/1u9F0xEadzD5Ljkz51U6Uulb4ZEeU-NyZ/view?usp=sharing
Please note that this is linux x86_64 executable. It won't work on windows.

**Comment by PRELVAS94** [comment]
> ```shell
> cd f1viewer/cmd
> ```

Worked on Mac Air M1! Ty

**Comment by Replica17** [comment]
Could someone please provide the commands to use this fork on macOS? using m1 macbook.
