### ISSUE TITLE
Log file being created in user's current directory rather than executable location

### ISSUE THREAD

**Issue by peskdale** [SoMuchForSubtlety/F1viewer#17]
The log file (log.txt) is created wherever the user was in their filesystem when they call f1viewer. I imagine this file to be created in the executable location, but setWorkingDirectory is not called until a few lines later.

If it's not possible for the location to be changed, then perhaps make logging to file a debug-only option?

**Comment by SoMuchForSubtlety** [comment]
fixed in https://github.com/SoMuchForSubtlety/F1viewer/commit/43f543b4cbed6193e95cd45eecb13840414f0ca8

thanks I overlooked that
