### ISSUE TITLE
[BUG] Cannot Build on macOS

### ISSUE THREAD

**Issue by dwwkelly** [SoMuchForSubtlety/f1viewer#174]
**Describe the bug**
I can't build this code on macOS.  Go can't find an .go files.  Also, a release for 2.0.6 would help.

**To Reproduce**
```
cd f1viewer
./macOS-build.sh
no Go files in <parent dir>/f1viewer
FAILED TO BUILD
```

**Expected behaviour**
Builds code

**Screenshots**
NA

**F1TV account plan**
Pro

**Desktop (please complete the following information):**
macOS Big Sur

**Logs**
NA

**Comment by joschiv** [comment]
Go into cmd folder. Then type:

go build

On my machine I got following error 

% go build                               
# github.com/keybase/go-keychain
../go/pkg/mod/github.com/keybase/go-keychain@v0.0.0-20201121013009-976c83ec27a6/corefoundation.go:8:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by SoMuchForSubtlety** [comment]
to build you need to run `go build cmd/main.go`, or simply run `go get github.com/SoMuchForSubtlety/f1viewer@master` from your home directory
