### ISSUE TITLE
New UI layout

### ISSUE THREAD

**Issue by obvionaoe** [SoMuchForSubtlety/f1viewer#175]
Hi was the change to the layout a conscious decision? I think it's a lot harder to navigate now...

Plus, in the new Homepage section it has the Grand Prix names in their own language making some of them hard to interpret.

If this was a change meant to stick, could we at least get a configuration that allows us to use the old UI?

Cheers, and sorry if it seems harsh, I do love all the work you've put into f1viewer!

**Comment by SoMuchForSubtlety** [comment]
The layout and titles are dictated by the F1TV API. I can check if the API provides alternative titles, but the layout would be hard to change significantly.

**Comment by obvionaoe** [comment]
Ah, alright I didn't know that! Bad decision on their side imho. Again, thanks for all your work! Streams in f1viewer are a lot better and more consistent than on the website!

**Comment by nsunderland1** [comment]
You can see why the layout is the way it is if you go to f1tv.formula1.com and then go to 2021 Season. At the top it shows you the next race, then "recent races", followed by "upcoming races", and then "previous races", which results in the super weird ordering you see in the f1viewer UI. I haven't looked at the API yet, but I assume it exposes this directory structure. If f1viewer broke it down similarly into current - recent - upcoming - previous I think that would go a long way to making it more readable.

**Comment by SoMuchForSubtlety** [comment]
https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v2.2.0 somewhat improved the situation. If you have suggestions for further improvements feel free to open a new issue.
