### ISSUE TITLE
[BUG] characters after symbols corrupts with LANG=zh_CN locale

### ISSUE THREAD

**Issue by nicholascw** [SoMuchForSubtlety/f1viewer#179]
**Describe the bug**
Items comes after a terminal symbol has its first letter corrupted.

**To Reproduce**
Install on Archlinux with AUR script.

**Expected behaviour**
Readable text.

**Screenshots**
![图片](https://user-images.githubusercontent.com/7414442/124219039-19b88b00-dac1-11eb-9f39-53e9c6c1f558.png)

**F1TV account plan**
TV pro w/o VPN.

**Desktop (please complete the following information):**
 - Arch Linux
 - Arch Linux AUR
 - Version 2.1.0

**Logs**
Nothing related to the issue for sure.

**Comment by SoMuchForSubtlety** [comment]
What terminal are you using? I can't reproduce the issue on arch with gnome terminal 3.40.2

**Comment by nicholascw** [comment]
Sorry I didnt see you commented.

On my two different latest Archlinux instances, aur/gnome-terminal-transparency 3.40.3-1 , community/guake 3.7.0-2 , extra/konsole 21.04.3-1 all have this issue. Both starting with Zsh and bash can reproduce the issue.

---

Just a quick try and found that `$ LANG=C f1viewer` solves the issue for me... If you'd like to investigate on what's really happening maybe try starting with  `LANG=zh_CN f1viewer` locale.

**Comment by SoMuchForSubtlety** [comment]
Can't reproduce by just setting `LANG`. 
![image](https://user-images.githubusercontent.com/15961647/127750516-cfda5fa1-ab86-4c30-8513-1cef45517399.png)


If I manage to reprocude the issue I will report a bug upstream in [tview](https://github.com/rivo/tview)

**Comment by nicholascw** [comment]
could you try `LANG=zh_CN.UTF-8` or `LC_ALL=zh_CN.UTF-8` ? I just found that mine with LANG=zh_CN also works while zh_CN.UTF-8 isn't.

**Comment by SoMuchForSubtlety** [comment]
It looks like this won't/can't be fixed upstream.

A workaround is to set the env var `RUNEWIDTH_EASTASIAN=true`, see https://github.com/mattn/go-runewidth/issues/14
