### ISSUE TITLE
Way to possible load custom .lua scripts for mpv

### ISSUE THREAD

**Issue by ChaosPaladin** [SoMuchForSubtlety/F1viewer#18]
Any way to launch custom .lua scripts with action MPV?

Currently i trying launch script https://gitlab.com/lvml/mpv-plugin-excerpt with config
```json
	{
            "title": "Play with MPV (Lua script)",
            "commands": [
		["mpv", "$url", "--alang=de --lua excerpt.lua"]
            ],
            "watchphrase": "Video",
            "command_to_watch": 0
        }
```

Scripts `excerpt.lua` and `excerpt_copy` placed in same directory as mpv/ffmpeg and commandline tell its loaded `mpv https://f1tv-cdn-cent-live.formula1.com/ondemand/ce1c/_C_/3/2/wif0630041637/1/clip_2_master.m3u8?nva=1562911769&ttl=86400&cc=&token=0a6cfda24a469e6be08aa "--alang=de --lua excerpt.lua"`, but script not work.

**Comment by SoMuchForSubtlety** [comment]
Each argument separated by a space must be in a separate string.
Try this:
```["mpv", "$url", "--alang=de", "--lua", "excerpt.lua"]```

**Comment by ChaosPaladin** [comment]
Thx, it works, also can be work with puting scripts to ./scripts/ dir in root mpv
