### ISSUE TITLE
[BUG] No seasons 2018-2020

### ISSUE THREAD

**Issue by SamPro910** [SoMuchForSubtlety/f1viewer#183]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
Cannot find seasons 2018-2020
**To Reproduce**
1. Enter f1viewer
2. IT'S NOT THERE!

**Expected behaviour**
Available races from 2018-2020

**Screenshots**
![pic-window-210719-1209-23](https://user-images.githubusercontent.com/79455895/126125750-811f42e1-91d3-4bbe-9dd3-27f9d1d26b56.png)

**F1TV account plan**
Do you have a free, access or pro account? Are you using a VPN / proxy?
F1TV Pro, no VPN

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - installation method: AUR
 - Version [`f1viewer -v` output] 2.1.0

**Comment by SoMuchForSubtlety** [comment]
Fixed in the next release (should be out shortly)

![image](https://user-images.githubusercontent.com/15961647/127750971-c9199269-ad05-4c5c-90e2-358b3d7b48a7.png)
