### ISSUE TITLE
[FEATURE] Ability to define the characters that get removed from $title

### ISSUE THREAD

**Issue by jeffcasavant** [SoMuchForSubtlety/f1viewer#184]
I use a custom FFmpeg command:

```
{
  "title": "FFMPEG Download",
  "command": [
      "ffmpeg", "-i", "$url", "-c", "copy", "-loglevel", "warning", "-stats", "$title.mp4"
  ]
}
```

But when I try to fetch titles containing a colon, this errors out (e.g. in the case of `2022: Everything You Need To Know`, ffmpeg thinks I'm trying to copy to a URI with the protocol `2022`).

I'd like at least a title var without a colon in it.  But it'd be even cooler if I could define the characters that get removed from the `$title` variable in config.

**Comment by SoMuchForSubtlety** [comment]
Have you tried setting the format explicitly? like this 
```json
{
  "title": "FFMPEG Download",
  "command": [
      "ffmpeg", "-i", "$url", "-c", "copy", "-loglevel", "warning", "-stats", "-f", "mp4", "$title.mp4"
  ]
}
```

**Comment by jeffcasavant** [comment]
Same issue with `-f` - but that did push me down the path of trying to make FFMPEG output to the filename that I want.  Using `"file:$title.mp4"` works!
