### ISSUE TITLE
[BUG] F1 TV Backend Change breaks playback

### ISSUE THREAD

**Issue by DanseMacabre** [SoMuchForSubtlety/f1viewer#186]
**Describe the bug**
Currently, playback with mpv are all broken due to this backend change. Before for retrieving the master playlist and all the media segments from the media playlists from the master playlist was as simple as doing a GET request to the segment/playlist. However, now it seems like F1TV wants to use cookie "playToken" to authenticate GET requests to content server. Most video clients (ffmpeg, mpv) doesn't seem to be able to set and send the cookie correctly. As a result, all content fail to load via the above mentioned players. VLC Media Player however is able to load the content without issue it seems like.

**To Reproduce**
Open any video stream with MPV.

**Expected behaviour**
Video Plays

**F1TV account plan**
Pro/Proxy, however this is irrelevant, see https://github.com/robvdpol/RaceControl/issues/210

**Desktop (please complete the following information):**
-win10
-chocolatey

**Logs**
See: https://github.com/robvdpol/RaceControl/issues/210

**Notes**
Some description copied from the related bug, and therefore might be incorrect!

**Comment by SoMuchForSubtlety** [comment]
I added support for proxying requests as a temporary workaround. https://github.com/SoMuchForSubtlety/f1viewer/commit/ddef349c72c532ee5674210792912e879ddfe11b

There will be a release before the weekend.
