### ISSUE TITLE
[BUG] Seen as Trojan by Windows 11 Defender Antivirus

### ISSUE THREAD

**Issue by luciodaou** [SoMuchForSubtlety/f1viewer#192]
As soon as I updated from Chocolatey to version 2.4.0, I got Windows Defender warning of a threat.

Trojan:Win32/Sabsik.TE.B!ml

![image](https://user-images.githubusercontent.com/53634214/139758362-88777e05-6190-47fc-9f5f-9f1d409d6324.png)

No problems with 2.3.0.

**Comment by SoMuchForSubtlety** [comment]
Go executables are often falsely detected as a virus[^1], I will investigate what specific change triggered the detection. Meanwhile, you can add an exception for f1viewer to windows defender.

[^1]: https://golang.org/doc/faq#virus
