### ISSUE TITLE
[BUG] KWallet no longer unlocks/provide password

### ISSUE THREAD

**Issue by andrejxa** [SoMuchForSubtlety/f1viewer#193]
KWallet no longer unlocks/provide password.
F1viewer also doesn't ask to unlock wallet.

 - Arch linux with KDE 5.23.2
 - installed with AUR
 - Version 2.4.0

ERROR message: could not get credentials: The name org.freedesktop.secrets was not provided by any .service files
Also have kwallet-secrets installed

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report, looks like the new package I use for credential management[^1] does not support that backend. I will see what I can do.

[^1]:https://github.com/SoMuchForSubtlety/f1viewer/commit/fe6920e70dbb4a988229c9298cd34319f8ab1437
