### ISSUE TITLE
[HELP] Download Videos Including All Audios - FFMPEG

### ISSUE THREAD

**Issue by Vallesuski** [SoMuchForSubtlety/f1viewer#196]
Hi, I have been downloading videos with FFMPEG in f1viewer based on following code -->

`		"command": ["ffmpeg", "-i", "$url", "-c", "copy", "$title.mp4"],
		`

What should be the right command line to use in order to download the file with all audios included?
As it is today only downloads 1 audio, not all of them.

How should look the command line?

Thanks for your help.

**Comment by Vallesuski** [comment]
I was able to download all audios reviewing these 2 issues already created -->

https://github.com/SoMuchForSubtlety/f1viewer/issues/100
https://github.com/SoMuchForSubtlety/f1viewer/issues/107

**Comment by losbeekos** [comment]
So what is your command @Vallesuski?

**Comment by Vallesuski** [comment]
> So what is your command @Vallesuski?

Since I like to download in 1080p quality I use this --> `ffmpeg -i URL -map 0:p:5 -c copy name.ts`
