### ISSUE TITLE
[BUG] Copy URL To Clipboard - Not Working

### ISSUE THREAD

**Issue by Vallesuski** [SoMuchForSubtlety/f1viewer#197]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
Copy URL to clipboard is not working. I get message "Error: exit status 1"
I have xsel, xclip and  wl-clipboard installed.

**To Reproduce**
1. Go to 2021 Season
2. Select any GP
3. Select any Replay
4. Select any feed
5. Select "Copy URL To Clipboard"

**Screenshots**
https://i.imgur.com/oLkTIyo.png

**F1TV account plan**
F1TV Pro Account
No VPN

**Desktop (please complete the following information):**
 - Ubuntu 20.04 Server
 - F1Viewer 2.4.0

**Logs**
No logs running `f1viewer -logs`.

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report!

Are you accessing the server over SSH? Does running `echo test | xclip -in -selection clipboard` put "test" into your clipboard?

**Comment by SoMuchForSubtlety** [comment]
To enable copy-pasting over ssh you need to enable X11 forwarding with the `-X` flag[^1]. That way xclip on the server has access to your X session (and your clipboard).

```bash
ssh -X user@server
```


[^1]: https://manpages.debian.org/bullseye/openssh-client/ssh.1.en.html#X

**Comment by Vallesuski** [comment]
Thanks for your reply.
