### ISSUE TITLE
No sound.

### ISSUE THREAD

**Issue by edtng** [SoMuchForSubtlety/F1viewer#2]
Hi,

I'm getting a video but it has no sound. Not sure if I'm missing something obvious but nothing I do seems to solve the issue.

Cheers

**Comment by SoMuchForSubtlety** [comment]
What operating system? Are you using F1Viewer to launch MPV? Does this happen for every video you try?

**Comment by edtng** [comment]
I'm using W10, F1Viewer won't automatically launch MPV so I'm using the .m3u8 files and yes I tested it with the 2019 Australia GP highlights vod too (along with the current qualy livestream) and got no sound.

**Comment by SoMuchForSubtlety** [comment]
Please try using the latest MPV version from here https://sourceforge.net/projects/mpv-player-windows/files/

**Comment by edtng** [comment]
Wasn't working despite being in the same folder but I added it to PATH and now it works. Thank you so much for the help (and for the great program).

**Comment by SoMuchForSubtlety** [comment]
no problem
