### ISSUE TITLE
[FEATURE] Automatically run custom command when new livestream is detected.

### ISSUE THREAD

**Issue by sembeek** [SoMuchForSubtlety/f1viewer#201]
**Is your feature request related to a problem? Please describe.**

I would like to automatically have a m3u updated when there is a new live stream detected.

**Describe the solution you'd like**

I have a custom command that adds a stream to a m3u file, but i have to do it manually everytime.
It would be awesome if there is a way to automatically run a custom command when a new livestream is detected.

**Describe alternatives you've considered**

Running the script trough crontab, but I could not get this to work.

**Additional context**

I am using this custom command:
```
 [[custom_playback_options]]
   command = ["/bin/sh", "-c", "echo \"#EXTINF:-1, $session\n$url\n\n\" >>playlist.m3u"]
   proxy   = true
   title   = "add track to playlist"
```

**Comment by SoMuchForSubtlety** [comment]
Thanks for the suggestion, this feature will be included in the next release

https://github.com/SoMuchForSubtlety/f1viewer#Live-session-hooks
