### ISSUE TITLE
[BUG] Proxy seems to stop after start up and stream does not work so

### ISSUE THREAD

**Issue by SkYNewZ** [SoMuchForSubtlety/f1viewer#204]
**Describe the bug**
I'm using IINA as player. This bug does not exist with VLC as it does not use the proxy.
So I clicked on the curent livestream, logs shows a proxy starting and immediately stops. So the url sent to IINA does not work since the proxy is not listening.

**To Reproduce**
1. Check for curent live streams
2. Start one with IINA
3. IINA receives a 127.0.0.1 url which does not work since the proxy is stopped

**Expected behaviour**
Simply run the stream.

**Screenshots**
https://asciinema.org/a/475653

**F1TV account plan**
Do you have a free, access or pro account? Yes
Are you using a VPN / proxy? No

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - installation method: brew
```
❯ f1viewer -v
Version:     2.5.0
Git commit:  aad74d9eeea99096b5b25cc0f82666d023671076
Built:       2021-12-01T17:51:11Z
```

**Logs**
```
2022/03/10 11:33:09 [INFO] subscription status: active
2022/03/10 11:33:09 [INFO] logged in!
2022/03/10 11:33:09 [INFO] checking for live session
2022/03/10 11:33:09 [INFO] found live event
2022/03/10 11:33:10 [INFO] loading details for 2022 Pre-Season Test - DAY 1, SESSION 1 (1000005273)
2022/03/10 11:33:12 [INFO] proxy listening at: 127.0.0.1:61733
2022/03/10 11:33:12 [INFO] proxy started
2022/03/10 11:33:12 [INFO] closing proxy
2022/03/10 11:33:12 [INFO] stopped proxy
2022/03/10 11:33:26 [INFO] subscription status: active
2022/03/10 11:33:26 [INFO] logged in!
2022/03/10 11:33:26 [INFO] checking for live session
2022/03/10 11:33:26 [INFO] found live event
2022/03/10 11:33:28 [INFO] loading details for 2022 Pre-Season Test - DAY 1, SESSION 1 (1000005273)
2022/03/10 11:33:30 [INFO] proxy listening at: 127.0.0.1:61763
2022/03/10 11:33:30 [INFO] proxy started
2022/03/10 11:33:30 [INFO] closing proxy
2022/03/10 11:33:30 [INFO] stopped proxy
…
```

**Comment by moritzsternemann** [comment]
I observe the same behavior with pretty much exactly the same setup.

**Comment by SkYNewZ** [comment]
By forcing proxy mode on VLC, the problem does not exist.

```diff
diff --git i/internal/cmd/cmd.go w/internal/cmd/cmd.go
index 4d9aead..2cdd5f4 100644
--- i/internal/cmd/cmd.go
+++ w/internal/cmd/cmd.go
@@ -96,6 +96,7 @@ func NewStore(customCommands []Command, multiCommands []MultiCommand, lang []str
                        registry32:   "SOFTWARE\\VideoLAN\\VLC",
                        Command:      []string{"vlc", "$url", "--meta-title=$title", "--audio-language=" + strings.Join(lang, ",")},
                        flatpakAppID: "org.videolan.VLC",
+                       Proxy:        true,
                },
                {
                        Title:   "Play with IINA",
```

The only difference I notice at the moment is that the `vlc` command runs in attached mode and until `cmd.Process.Wait()` returns, the proxy will not be stopped. `iina` runs in detached/background mode so `cmd.Process.Wait()` is called immediately, the context is cancelled and the proxy server stops.

**Comment by nocturne1** [comment]
I see exactly the same thing here.  At least until this is fixed, adding a custom playback option (by default, uses proxy=false) seems to work around this.

```
[[custom_playback_options]] 
command = ["iina", "--no-stdin", "$url"]
title = "Play with IINA - no proxy"
```
