### ISSUE TITLE
[BUG] Theme colours not changing v2.5.0

### ISSUE THREAD

**Issue by meteordust** [SoMuchForSubtlety/f1viewer#208]
Hi,

After updating or reinstalling v.2.5.0 the override of the theme colours are not changing when I set other hex colours in the new config.toml file like it did with previous versions.

I tried did on several Windows 10 Pro/ Home versions, 64 bit.

Some text colours like dark blue are unreadable with the dark background with the standard setting.

Thanks in advance

**Comment by SoMuchForSubtlety** [comment]
Thanks for reporting the issues, this was already fixed and I will release a new version this week.

see #207
