### ISSUE TITLE
[BUG] Multi Commands & Live Stream Hooks missing variables

### ISSUE THREAD

**Issue by christovic** [SoMuchForSubtlety/f1viewer#209]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**

When using multi commands & live stream hooks, the variables are not passed through to the script. $lang and $url are passed through.

**To Reproduce**
My sub-optimal, but working config: 
```
[[multi_commands]]
  title = "World & Data"

  [[multi_commands.targets]]
    match_title = "World Feed"
    proxy   = true
    command = ["./ffmpeg.sh", "$url", "World Feed"]

  [[multi_commands.targets]]
    match_title = "Data Channel"
    proxy = true
    command = ["./ffmpeg.sh", "$url", "Data Channel"]

  [[multi_commands.targets]]
    match_title = "Pit Lane"
    proxy = true
    command = ["./ffmpeg.sh", "$url", "Pit Lane"]

  [[multi_commands.targets]]
    match_title = "Driver Tracker"
    proxy = true
    command = ["./ffmpeg.sh", "$url", "Driver Tracker"]
```
What I think should work:
```
[[custom_playback_options]]
  command = ["./ffmpeg.sh", "$url", "$perspective", "$title"]
  proxy   = true
  title   = "Restream"

[[multi_commands]]
  title = "World & Data"

  [[multi_commands.targets]]
    match_title = "World Feed"
    proxy   = true
    command_key = "Restream"

  [[multi_commands.targets]]
    match_title = "Data Channel"
    proxy = true
    command_key = "Restream"

  [[multi_commands.targets]]
    match_title = "Pit Lane"
    proxy = true
    command_key = "Restream"

  [[multi_commands.targets]]
    match_title = "Driver Tracker"
    proxy = true
    command_key = "Restream"
```
Run a multi command with some variables like $title and $session

**Expected behaviour**
Same behaviour as Custom Commands

**Screenshots**
The return of $json:
```
{
	"PerspectiveTitle": "World \u0026 Data",
	"Event": "",
	"Category": "",
	"Title": "",
	"Session": "",
	"Date": "0001-01-01T00:00:00Z",
	"Year": "",
	"Country": "",
	"Series": "",
	"EpisodeNumber": 0,
	"OrdinalNumber": 0,
	"Circuit": "",
	"Source": null
}
```

**F1TV account plan**
Do you have a free, access or pro account? Are you using a VPN / proxy?
Pro, VPN

**Desktop (please complete the following information):**
 - OS
 Debian/Docker
 - installation method
 .deb package
 - Version [`f1viewer -v` output]
 2.6.0

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report, I'll investigate.

**Comment by christovic** [comment]
Just built and works perfectly now, thanks so much Jakob! Did have a peek at the code myself but I'm not familiar with Go or anything close to it so looking at your commit was really helpful :)
