### ISSUE TITLE
Live session stoped show as first in list

### ISSUE THREAD

**Issue by ChaosPaladin** [SoMuchForSubtlety/F1viewer#21]
![image](https://user-images.githubusercontent.com/10120702/64472418-b41a4280-d166-11e9-9119-88708f24473c.png)
![image](https://user-images.githubusercontent.com/10120702/64472420-bd0b1400-d166-11e9-8053-47ad3cbc31a9.png)

**Comment by SoMuchForSubtlety** [comment]
Yea the F1TV api changed. I'll release an update.

**Comment by SoMuchForSubtlety** [comment]
fixed in e210218
released in [v0.7.2](https://github.com/SoMuchForSubtlety/F1viewer/releases/tag/v0.7.2)
