### ISSUE TITLE
[BUG] Live sessions do not seem to 're-load' on their own

### ISSUE THREAD

**Issue by synegic** [SoMuchForSubtlety/f1viewer#213]
First of all, thanks for your hard work on this program. It fits my use-case just perfectly.

**Describe the bug**
I am using your application on my home server to start up a casting session to the TV in my home office whenever a race begins. However, it seems that the live status never is cleared. This means for any subsequent live sessions, the live hooks do not execute.

**To Reproduce**
Start the program on the day of the training (e.g. Friday), it will run the live hooks as intended. Wait a couple of days, keep the program in the background. Notice that the program displays the old session title (in green on the top of the program), instead of the current actual live programme.

**Expected behaviour**
Re-set the 'live' status (and therefor re-load the live hooks) as soon as each broadcast session is finished/ended.

It would also be awesome if you could add 'live end hooks' as well, so it is possible to cleanly 'shut down'/end any automations that have been started with the live hook (e.g. cancel/stop the casting).

**F1TV account plan**
Pro, no VPN.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - installation method: deb
 - Version: 2.6.0 release for Linux

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report. I'll fix it before the next race :wink:

**Comment by synegic** [comment]
Thanks for the quick fix! Really appreciated.
