### ISSUE TITLE
[BUG] The F1 Live feed not available.

### ISSUE THREAD

**Issue by DominykasPetke** [SoMuchForSubtlety/f1viewer#218]
**Describe the bug**
The F1 Live feed (changed from the Pit Lane Channel) not showing up for Saudi Arabia FP1 (and potentially on-wards)

**To Reproduce**
1. Go to the live session
2. Neither the Pit Lane Channel nor the F1 Live channel is showing 

**Expected behaviour**
The F1 Live Channel is available (was under the Pit Lane Channel for the Bahrain GP weekend)

**F1TV account plan**
Pro Account, no VPN

**Desktop (please complete the following information):**
 - Arch, installed from the AUR
 - Version 2.6.0

**Comment by MarkusTheOrt** [comment]
Seems like a simple fix, the new title in the API is `F1 LIVE`
which would need to be changed here: https://github.com/SoMuchForSubtlety/f1viewer/blob/master/pkg/f1tv/v2/api.go#L220

However there is also a new v3 api slug.

**Comment by anthonylavado** [comment]
Issue was picked up at Race Control as well:

https://github.com/robvdpol/RaceControl/issues/387
