### ISSUE TITLE
no config file created after install (macOS) [BUG]

### ISSUE THREAD

**Issue by pananasx** [SoMuchForSubtlety/f1viewer#220]
Hi. 

I have installed F1viewer using Homebrew. It runs perfectly fine after launching it through terminal (w F1TV PRO subscription). However, no config file has been made.

After uninstalling F1viewer using Homebrew and doing a fresh install, the problem persists; no config file will be made. 
Also, ''$HOME/Library/Application Support/f1viewer'' does not seem to be present after install. This map is nowhere to be found on my device.
`f1viewer -config` or `f1viewer -logs` does not show anything. 

edit: also tried launching after downloading the binary directly. F1viewer runs but does not create config file. 

Am I doing something wrong during install which causes this issue? 

I'm using: 
MacBook Pro (late 2013)
2,3GhZ quad core intel i7
MacOS Big Sur version 11.6.1

F1viewer 2.6.0

Thx in advance.

**Comment by elgringo122** [comment]
Hi,

I also have the same issue, impossible to find the config file

I'm using a macbook pro 2019
1,4 GHz Intel Core i5 
MacOs Monterey version 12.2.1

Thanks for any answers that could help !

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report, I'll try to reproduce the issues in a macOS VM. When you start f1viewer, do any error messages show up in the box on the right?

**Comment by pananasx** [comment]
I don't see any error messages showing up in the box on the right. 
Thanks for looking into it.

**Comment by SoMuchForSubtlety** [comment]
I can't reproduce the issue on a fresh macOS Big Sur VM and f1viewer 2.6.2. Starting f1viewer generates `settings.toml` in `~/Library/Application Support/f1viewer/` as expected.

**Comment by pananasx** [comment]
Thanks for the help, too bad you couldn't reproduce the issue.
