### ISSUE TITLE
[BUG] Gives a Albon OBC for all options of a race session.

### ISSUE THREAD

**Issue by nicholascw** [SoMuchForSubtlety/f1viewer#222]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
With v2.6.1 built with AUR PKGBUILD running on Arch Linux, it gives a Albon OBC for all options (Data Channel, F1 Live, International, and other OBC options).

**To Reproduce**
Simply run f1viewer and click on (~~actually mouse click seems to be broken as well, have to use keyboard for 2.6.1~~ saw that `enable_mouse` option, but as it's added feature maybe considering make enabled as default behavior?) any channel for any 2022 race sessions.

**Expected behaviour**
Should give respective stream for each race session.

**Screenshots**
![图片](https://user-images.githubusercontent.com/7414442/160259422-fa868f76-f959-40f7-9748-caf525469d81.png)

**F1TV account plan**
Do you have a free, access or pro account? Are you using a VPN / proxy?

In USA using F1TV pro.

**Desktop (please complete the following information):**
 - OS Archlinux
 - installation method AUR ([here](https://mirrors.nw.ci/nicholascw-archrepo/x86_64/f1viewer-2.6.1-1-any.pkg.tar.zst) is the exact binary package build)
 - Version [`f1viewer -v` output] 2.6.1

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.

**Comment by Karyudo** [comment]
Came here to say the same thing. Just updated to 2.6.1 (Chocolatey) and found that all Saudi Arabia Qualifying streams are Albon at 720p. Qualifying Highlights plays fine. In Canada, F1TV Pro, Windows 10, MPV, no deliberate proxy.

Also had the "mouse doesn't work" issue, but a reinstall seems to have fixed that.

**Comment by Karyudo** [comment]
Manually reverting to 2.6.0 works just fine.

**Comment by hhejkhalkfahjahsf** [comment]
Yes, Albon is everywhere! Heeeelp!

**Comment by SoMuchForSubtlety** [comment]
fixed by 26612d36de96b5d484ed2d48e8b9daa412d624d1 new release with the fix is building.
