### ISSUE TITLE
Open in Elmedia Video Player

### ISSUE THREAD

**Issue by Jorritboer** [SoMuchForSubtlety/f1viewer#224]
Elmedia Video Player is my video player of choice on mac but I'm unable to get it working as a custom command. 
```
[[custom_playback_options]] 
  command = ["open", "-a", "elmedia video player", "$url"] 
  proxy   = true 
  title   = "Open in Elmedia Video Player"
```
This just opens Elmedia Video Player, and subsequently opens safari with the selected link

**Comment by Jorritboer** [comment]
Yes it does work that way. I should have mentioned that

**Comment by SoMuchForSubtlety** [comment]
I'm afraid there's not much I can do. You'll have to ask the authors of Elmedia Video Player for help.
Please report back if you manage to make it work.

**Comment by Jorritboer** [comment]
Yes will do, thanks for looking into it anyway!
