### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VirginianViking** [SoMuchForSubtlety/f1viewer#236]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
Cannot stream any live sessions. Screen is gray and there is no audio. 

**To Reproduce**
Attempt to stream any event

**Expected behaviour**
the live stream should play

**Screenshots**

**F1TV account plan**
Pro. No proxy

**Desktop (please complete the following information):**
 Windows 10
 downloaded exe from github
 - Version newest on github downloaded today. 
![Capture](https://user-images.githubusercontent.com/7518630/162559630-488ee99b-c814-4f97-86e5-5d81bebb3654.PNG)

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.
[2022-04-09.log](https://github.com/SoMuchForSubtlety/f1viewer/files/8456386/2022-04-09.log)

**Comment by nicholascw** [comment]
#233
