### ISSUE TITLE
$name for commands

### ISSUE THREAD

**Issue by LsHallo** [SoMuchForSubtlety/F1viewer#24]
I would really like to have the name of the event i'm playing as a variable when issuing a command. For example if i'm playing back the "Formula 1 Gran Premio De Mexico - F1 Race - Main Feed" i would like to have the $name parameter to be exactly that. This would make saving files a lot more convenient.  

Thanks in advance.

**Comment by SoMuchForSubtlety** [comment]
Good idea, I'll get on it.

**Comment by SoMuchForSubtlety** [comment]
I finally go to implementing this, you can review the details [here ](https://github.com/SoMuchForSubtlety/F1viewer/tree/rewrite#custom-commands)

Please let me know if you have any feedback or change requests :)

**Comment by LsHallo** [comment]
So far it works fine. Very nice job.
On a nother note I noticed that if I have a malformed config (forgot the closing ] in my custom_playback_options like so:
```
{
	"live_retry_timeout": 60,
	"preferred_language": "en",
	"check_updates": true,
	"save_logs": true,
	"log_location": "",
	"download_location": "",
	"custom_playback_options": [
		{
			"title": "download with ffmpeg",
			"command": ["ffmpeg", "-i", "$url", "-c:v", "hevc_nvenc", "-c:a", "copy", "$title.mp4"]
		},
	"horizontal_layout": false,
	"theme": {
		"background_color": "",
		"border_color": "",
		"category_node_color": "",
		"folder_node_color": "",
		"item_node_color": "",
		"action_node_color": "",
		"loading_color": "",
		"live_color": "",
		"update_color": "",
		"no_content_color": "",
		"info_color": "",
		"error_color": "",
		"terminal_accent_color": "",
		"terminal_text_color": ""
	}
}
```
The viewer will then check for a live session as fast as it can and I don't think that should be the behavior in such a case.

**Comment by SoMuchForSubtlety** [comment]
thanks for catching that, it's fixed with https://github.com/SoMuchForSubtlety/F1viewer/commit/d96cdac8bda47aeb8369b5b0f539ed5e5e894114
