### ISSUE TITLE
Login with my own account?

### ISSUE THREAD

**Issue by bfayers** [SoMuchForSubtlety/F1viewer#25]
I have an F1TV Pro account, trying to work out how to sign into this with my own account?

If it requires recompiling that's fine, I can do that.

**Comment by SoMuchForSubtlety** [comment]
Why do you want to sign in?

**Comment by bfayers** [comment]
Because I want to use my account that I pay for? Or does this just bypass the need for an account anyway?

**Comment by SoMuchForSubtlety** [comment]
Yes, there is no need to log in at the moment. If f1tv ever increases security measures I will add a way to log in.
