### ISSUE TITLE
Add option to select audio and video track if multiple are available

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [SoMuchForSubtlety/F1viewer#26]
use ffprobe get options, then select one

**Comment by LsHallo** [comment]
You could use ffprobe like this: `ffprobe -v quiet -print_format json -show_programs -i $url`
Which will result in the following sample output:
https://gist.github.com/LsHallo/74eb8debb6e52899786dca32ff1de88d

**Comment by SoMuchForSubtlety** [comment]
Yea I know.
I'm debating if I actually want to add this. ffprobe usually takes a really long tine with f1tv streams so it would be pretty annoying to use. MPV should pick a fitting video stream automatically anyways and you can set the audio language in the config.

This is on hold until I can think of a good use case or someone requests it with a good reason.

**Comment by LsHallo** [comment]
Yeah I see where you're at. I think it is fine as it is and if you would want a quality selector of some sort you can always use the custom command function and supply the url to a custom script which outputs some sort of quality selection. That would be on the part of the user. Your program could never cover any use case a quality/stream selection could have.
