### ISSUE TITLE
":" in $name

### ISSUE THREAD

**Issue by LsHallo** [SoMuchForSubtlety/F1viewer#29]
I've noticed that when I try to use the new $name attribute I sometimes run into problems if the name contains ":" since windows does not like that in file names.
Maybe you could replace invalid characters?

**Comment by SoMuchForSubtlety** [comment]
Good call. I'll remove reserved characters. 
thanks :)

**Comment by SoMuchForSubtlety** [comment]
this is fixed in cf442033b422780175cfc6c73f5c4e5242f69fba

**Comment by LsHallo** [comment]
Thank you for your effort. Very much appreciated!
