### ISSUE TITLE
Full list not loading somewhy

### ISSUE THREAD

**Issue by ChaosPaladin** [SoMuchForSubtlety/F1viewer#34]
Some time ago tool stop loading full list and directories v0.7.3 win64
![image](https://user-images.githubusercontent.com/10120702/73508914-7b695700-43ee-11ea-8650-8df7ade6cc62.png)

**Comment by SoMuchForSubtlety** [comment]
I can't reproduce the issue, can you send me the logs? They should be in the same directory as F1viewer.

**Comment by ChaosPaladin** [comment]
https://gist.github.com/ChaosPaladin/2dce9134b20f7d41e76529283b300d7f

**Comment by SoMuchForSubtlety** [comment]
Does this page load for you? https://f1tv.formula1.com/api/vod-type-tag/

**Comment by ChaosPaladin** [comment]
https://gist.github.com/ChaosPaladin/09a74f4e9b89cfcc37d2e5373bd5c833

**Comment by SoMuchForSubtlety** [comment]
Are the `content_urls` lists actually empty or did you remove them?

**Comment by ChaosPaladin** [comment]
> Are the `content_urls` lists actually empty or did you remove them?

Empty

**Comment by SoMuchForSubtlety** [comment]
Hmm, yea they seem to be blocking based on location now. I'm afraid the only workaround for now is a VPN.

I will try to find a solution but I'm not optimistic. What country are you in?

**Comment by ChaosPaladin** [comment]
> Hmm, yea they seem to be blocking based on location now. I'm afraid the only workaround for now is a VPN.
> 
> I will try to find a solution but I'm not optimistic. What country are you in?

Belarus
![image](https://user-images.githubusercontent.com/10120702/73572797-be750a00-4482-11ea-896b-ba3aca0dd3f5.png)

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report. I'll let you know if I figure something out.
