### ISSUE TITLE
F1TV requires authentican to generate streamable URL

### ISSUE THREAD

**Issue by apok-f1** [SoMuchForSubtlety/f1viewer#36]
After updating to Catalina, I now get the following errors
![Screenshot 2020-02-10 at 14 49 42](https://user-images.githubusercontent.com/60887105/74159985-99b42b80-4c14-11ea-9d1f-2f57e9b0ed6f.png)

Any ideas?

**Comment by apok-f1** [comment]
From the logs 

`2020/02/10 14:49:07 [ERROR] {"form_validation_errors": null, "skylark_error_code": null, "error": "{\"form_validation_errors\": null, \"skylark_error_code\": null, \"error\": \"driver_urls was not in the fields to be returned. Has it been filtered out? (Available fields: name, self)\"}"}`

**Comment by apok-f1** [comment]
![Screenshot 2020-02-10 at 15 50 22](https://user-images.githubusercontent.com/60887105/74165517-24008d80-4c1d-11ea-8574-4331ddf7ed9e.png)

Also getting error on the VOD. 

I will try VPN later today! :)

**Comment by SoMuchForSubtlety** [comment]
F1TV was updated so F1viewer is broken. You now need a login. I will try to find a fix but it is not very likely.

**Comment by SoMuchForSubtlety** [comment]
The latest commit adds an option to log  in if you have an F1TV pro account. 0f6d89222741f1ce9f6f7514b7d77722be65aff2
