### ISSUE TITLE
Update with authentication

### ISSUE THREAD

**Issue by LsHallo** [SoMuchForSubtlety/F1viewer#39]
Is there any possibility you can update the program using the official authentication method?
I could not find a way to download videos with ffmpeg now that it is restricted. Would love to do that again.

**Comment by SoMuchForSubtlety** [comment]
Yea that's the plan, I will work on it this weekend.

**Comment by SoMuchForSubtlety** [comment]
The latest commit  adds F1TV authentication. 0f6d89222741f1ce9f6f7514b7d77722be65aff2
Please let me know if there are any issues.
