### ISSUE TITLE
$url substitution replaces original string

### ISSUE THREAD

**Issue by peskdale** [SoMuchForSubtlety/F1viewer#4]
The replacement of $url in custom commands only works the first time it is triggered. Subsequent uses of the same custom command result in the previous url being returned again, as it has replaced the original string in the stored argument.

**Comment by SoMuchForSubtlety** [comment]
You're right, I'll fix that. 
I also saw you change in 2017df81f17d8acb77bf5154550527a14959c5cd and will add that too.

**Comment by peskdale** [comment]
Thanks for taking the time to implement these features. Making it a lot easier to watch on my TV.

**Comment by SoMuchForSubtlety** [comment]
should be fixed with f1940204344c392bb29f9683fd732ba4808a311a 
let me know if there are any other issues :)
