### ISSUE TITLE
F1viewer crashes

### ISSUE THREAD

**Issue by neezerr** [SoMuchForSubtlety/f1viewer#41]
After few seconds it crashes, logs say there's missing config.json. Tried to create this config and nothing helped. 
edit: Ok, i fixed config thing but it still crashes. logs are:
found 0 custom commands
checking for live session
no update available 
That’s all, it worked for the whole 2019 season. It started crashing early 2020, yesterday after reinstall i’ve had that config problem however, i fixed it by saving the file as .json and it’s crashing again like in the past

**Comment by SoMuchForSubtlety** [comment]
What version are you using?

**Comment by neezerr** [comment]
0.7.3 windows 64-bit
same issue on two computers. is it possible that i’m missing any file?

**Comment by neezerr** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/61496210/75342088-00cd1380-5896-11ea-827c-a6aa390dc488.png)
my files

**Comment by SoMuchForSubtlety** [comment]
That version won't work anyways since F1TV now requires a login to play videos.

I can take a closer look later this afternoon.

**Comment by neezerr** [comment]
is there any version that works now?

**Comment by SoMuchForSubtlety** [comment]
I will release 1.0.0 shortly. Meanwhile you can build it yourself.

You need a F1TV pro account to stream videos now.

**Comment by neezerr** [comment]
f1 tv pro subscription or only account?

**Comment by SoMuchForSubtlety** [comment]
You need a pro or access account

**Comment by aaradi** [comment]
Can it be used to view live stream in an unsupported territory (with pro account)?

**Comment by SoMuchForSubtlety** [comment]
I have not tested that extensively but it should work if you use a VPN, otherwise the F1TV API does not return anything.
