### ISSUE TITLE
Application won't launch; could not access credential store

### ISSUE THREAD

**Issue by bottaswmr** [SoMuchForSubtlety/f1viewer#44]
Installed from Homebrew on MacOS 10.15. When I run `f1viewer` from the command line, it returns the error:
`[ERROR] Could not access credential store: Specified keyring backend not available`

Here's the log:
[2020-03-14.log](https://github.com/SoMuchForSubtlety/f1viewer/files/4332991/2020-03-14.log)

**Comment by SoMuchForSubtlety** [comment]
Yea that seems to be a bug introduced with Catalina. I'll have a fix soon. Definitely before the season starts ;)

**Comment by SoMuchForSubtlety** [comment]
[The new release fixes this](https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v1.1.0)

**Comment by bottaswmr** [comment]
Got it done before lights out 👍
