### ISSUE TITLE
Crash on Full Race Weekend Race Video List

### ISSUE THREAD

**Issue by LsHallo** [SoMuchForSubtlety/f1viewer#48]
**Describe the bug**
When trying to list the playback options for a race of the type "Full Race Weekend" the program crashes. Full Races (not the whole weekend) (pre 2018) work just fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Full Race Weekend > 20xx F1 Championship > xx Grand Prix > Race > Crash'

**Expected behaviour**
List the options for the race.

**Screenshots**
![image](https://user-images.githubusercontent.com/22171518/84281615-14487580-ab39-11ea-97d3-daf6c5f108ee.png)
`loading...` and then crashes.

**Desktop (please complete the following information):**
 - Windows 10 2004 (Build 19041.329)
 - Latest release binary and `go build` on lastest master
 - Version 1.0.0 and dev

**Logs**
These are the logs repeating the crash a few times. Nothing to speak of really.
```
2020/06/10 15:59:15 [INFO] logged in!
2020/06/10 15:59:15 [INFO] checking for live session
2020/06/10 15:59:18 [INFO] no live session found
2020/06/10 15:59:36 [INFO] logged in!
2020/06/10 15:59:36 [INFO] checking for live session
2020/06/10 15:59:38 [INFO] no live session found
2020/06/10 16:02:34 [INFO] logged in!
2020/06/10 16:02:34 [INFO] checking for live session
2020/06/10 16:02:37 [INFO] no live session found
2020/06/10 16:04:43 [INFO] logged in!
2020/06/10 16:04:43 [INFO] checking for live session
2020/06/10 16:04:44 [INFO] New version found!
2020/06/10 16:04:46 [INFO] no live session found
2020/06/10 16:39:38 [INFO] logged in!
2020/06/10 16:39:38 [INFO] checking for live session
2020/06/10 16:39:39 [INFO] New version found!
2020/06/10 16:39:40 [INFO] no live session found
```

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report, I'll take a look

**Comment by LsHallo** [comment]
Here is my config if that's any help.
```
{
	"live_retry_timeout": 500,
	"preferred_language": "en",
	"check_updates": true,
	"save_logs": true,
	"log_location": "",
	"custom_playback_options": [
		{
			"title": "ffmpeg",
			"command": ["python", "ffdown.py", "$url", "$title.mkv"]
		},
		{
			"title": "ffmpeg (no reencode)",
			"command": ["python", "ffdown.py", "$url", "$title.mkv", "--direct"]
		}
	],
	"horizontal_layout": false,
	"theme": {
		"background_color": "",
		"border_color": "",
		"category_node_color": "",
		"folder_node_color": "",
		"item_node_color": "",
		"action_node_color": "",
		"loading_color": "",
		"live_color": "",
		"update_color": "",
		"no_content_color": "",
		"info_color": "",
		"error_color": "",
		"terminal_accent_color": "",
		"terminal_text_color": ""
	},
	"tree_ratio": 1,
	"output_ratio": 2
}
```

**Comment by LsHallo** [comment]
I could successfully get this error message:
```
loading...panic: runtime error: slice bounds out of range [1:0]

goroutine 171 [running]:
.getPerspectiveNodes
```

**Comment by aronday** [comment]
I also get the same errors on anything within the race weekend area. VOD works fine

**Comment by apok-f1** [comment]
I get the same issue. I can confirm the VOD works fine we no issues

**Comment by SoMuchForSubtlety** [comment]
[The new release fixes this](https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v1.1.0)
