### ISSUE TITLE
APIs for F1Viewer

### ISSUE THREAD

**Issue by WalrusPUNCH** [SoMuchForSubtlety/f1viewer#49]
What APIs are you using for this project? Where it's possible to read their documentations?

**Comment by balexandre** [comment]
you mean this?

https://github.com/SoMuchForSubtlety/f1viewer/blob/master/api.go#L13

**Comment by LsHallo** [comment]
As far as I can tell it also relies heavily on https://github.com/SoMuchForSubtlety/golark
Which is an api for skylark (https://www.skylarkcms.com/) which F1TV seems to be using

**Comment by SoMuchForSubtlety** [comment]
The previous commenters are correct

I'm using the API the official web app uses too. The API is not documented, I found the endpoints by watching the calls being made. 

There is a newer endpoint now that the web app uses, but the old one still works.

old endpoint: https://f1tv.formula1.com/api/
new endpoint: https://f1tv-api.formula1.com/agl/1.0/unk/en/all_devices/

I use this library to make the calls https://github.com/SoMuchForSubtlety/golark

**Comment by SoMuchForSubtlety** [comment]
You can try it out like this https://play.golang.org/p/Si_AOXa3eqz
