### ISSUE TITLE
Control on Windows

### ISSUE THREAD

**Issue by 1nval1d** [SoMuchForSubtlety/f1viewer#51]
Hello,
how are you supposed to control the tool? On windows 10 it does not take any key inputs nor can I find any doc about it. I can log in but not select anything else.

**Comment by ragnos** [comment]
You navigate using the arrow keys. Works for me using Powershell and cmd, both standalone or via Windows Terminal app.

**Comment by jebedius** [comment]
I think you just need a numpad

**Comment by LsHallo** [comment]
@jebedius Why would a numpad help?
To disable it and use the arrow keys on there?
You can use the standard arrow keys, no numpad needed.

Can also confirm that it works with cmd, powershell on win10 and bash on ubuntu server 18.04.
v1.0 and v1.1.0 tested

**Comment by SoMuchForSubtlety** [comment]
You navigate using arrow keys, tab and enter.
