### ISSUE TITLE
[BUG] Crash on Austrian GP Practice 1 List Options

### ISSUE THREAD

**Issue by LsHallo** [SoMuchForSubtlety/f1viewer#52]
**Describe the bug**
Similar Bug to #48. When I select the Austrian GP 2020, Practice 1 the program crashes.
Bug is also reintroduced on 2019 Full Race Weekends as in #48

**To Reproduce**
Select 2020 Austrian GP Practice 1

**Expected behaviour**
List options to play with mpv, copy url etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Downloaded v1.1.0 from Github
 - Version 1.1.0

**Logs**
```
2020/07/03 13:09:43 [INFO] logged in!
2020/07/03 13:09:43 [INFO] checking for live session
2020/07/03 13:11:32 [INFO] logged in!
2020/07/03 13:11:32 [INFO] checking for live session
2020/07/03 13:12:15 [INFO] logged in!
2020/07/03 13:12:15 [INFO] checking for live session
```

**Comment by SoMuchForSubtlety** [comment]
Thanks for the report I'll take a look.

**Comment by SoMuchForSubtlety** [comment]
I can't reproduce the issue. What exactly did you do to cause the crash?

![image](https://user-images.githubusercontent.com/15961647/86468654-297b8300-bd38-11ea-8e8c-3dcc7deae553.png)

**Comment by LsHallo** [comment]
I just figured out that i have f1viewer.exe 1.1.0 and if I run it in powershell it opens another, older version. That was the cause of the crash. Closing this as it is not related to f1viewer and fixed already.
