### ISSUE TITLE
Can't play many videos including live sessions

### ISSUE THREAD

**Issue by aaradi** [SoMuchForSubtlety/f1viewer#53]
I got the latest version, 1.1.
Getting the following error:
`[ERROR] got status 400 Bad Request with body:
{"skylark_error_code": null, "form_validation_errors": null, "error": "The content must have a schedule that matches the current schedule filters"}`

**Comment by LsHallo** [comment]
I can play the current F2 Practice session without problem with mpv.
Maybe try deleting your credentials from windows / linux key chain and reentering them.

**Comment by alanwHOME** [comment]
Lol!
Beat me to it.
🥇

**Comment by LsHallo** [comment]
Also mentioning #42 here since it seems related.

Does anybody of you only have F1TV access and not F1TV Pro?

**Comment by alanwHOME** [comment]
Just basic F1TV access.

**Comment by LsHallo** [comment]
You can't watch live sessions with F1TV access.

**Comment by alanwHOME** [comment]
Doesn't work for the recording of F1 First Practice either:
![image](https://user-images.githubusercontent.com/47475582/86466177-131afa80-bd2b-11ea-8314-5a476639f460.png)

**Comment by alanwHOME** [comment]
> You can't watch live sessions with F1TV access.

As in I have to subscribe to this:
![image](https://user-images.githubusercontent.com/47475582/86466505-a6ecc680-bd2b-11ea-938c-5e05da20385e.png)

**Comment by SoMuchForSubtlety** [comment]
You need F1TV pro to watch live broadcasts and F1TV access to watch replays.

Some users report being able to watch streams without access or pro subscription, but this varies and I have not figured out what determines this.

**Comment by LsHallo** [comment]
> Doesn't work for the recording of F1 First Practice either:
> ![image](https://user-images.githubusercontent.com/47475582/86466177-131afa80-bd2b-11ea-8314-5a476639f460.png)

Interesting that you can view options for that session. Crashes on my side as stated in #52
