### ISSUE TITLE
[New Feature] F1TV Now has 50fps 720p streams on a different URL/api

### ISSUE THREAD

**Issue by TheDevFreak** [SoMuchForSubtlety/f1viewer#55]
Via this URL a different (more basic) player is used that only shows the main feed, however it has 1280x720 at 50fps.

https://f1tv.formula1.com/dr/index.html

and this url nets you a JSON file with an m3u8 url: https://f1tv.formula1.com/dr/stream.json

**Comment by LsHallo** [comment]
According to ffprobe it also seems to be 9.5Mbit/s instead of the 5.5-6Mbit/s of the normal 1080p stream.

**Comment by TheDevFreak** [comment]
Yes, it seems very interesting @LsHallo it also appears to be using an entirely different CDN.

**Comment by LsHallo** [comment]
But it still seems to have some issues:
![image](https://user-images.githubusercontent.com/22171518/86477138-1f618080-bd48-11ea-897c-5b90c23ebf57.png)

**Comment by TheDevFreak** [comment]
Perhaps slightly offtopic but this seems to be the new CDN providers:

https://m2amedia.tv/

They recently posted about something called M2A connect here: https://m2amedia.tv/2020/05/18/m2a-media-launches-m2a-connect-leveraging-aws-elemental/

With this image as the thumbnail:
![image](https://user-images.githubusercontent.com/24739570/86477238-ea513000-bd3f-11ea-8801-ec99948d527a.png)

**Comment by SoMuchForSubtlety** [comment]
very interesting, thanks!

**Comment by PeteSeta** [comment]
Press release:
https://m2amedia.tv/2020/07/06/formula-1-chooses-m2a-connect-to-distribute-live-race-streams-to-broadcast-and-ott-partners/

**Comment by TheDevFreak** [comment]
@PeteSeta interesting - I wonder if they're justing using M2A to do the Track->FOM Servers link since I've heard about a staging f1tv that uses a Vodafone cdn

**Comment by PeteSeta** [comment]
@TheDevFreak Here was the attached image: https://m2amedia.tv/wp-content/uploads/2020/07/M2A-CONNECT_F1-Red-Bull-Ring_Austria_050720.png (can't attach due to file size); and can you please clarify about "a staging f1tv"?

**Comment by SoMuchForSubtlety** [comment]
Added support for this with c6ee1ce15a60eb6e7efb337456619ebf3f1a92ad
