### ISSUE TITLE
[NEW FEATURE] Show have a "Refresh" option so we can get ride of the Live Session when it ends

### ISSUE THREAD

**Issue by balexandre** [SoMuchForSubtlety/f1viewer#56]
When a live session ends, it will stay there forever as it does not re-fetch the data... maybe adding a Refresh item to the end of the menu? or keep pooling every minute?

for now <kbd>Ctrl</kbd> + <kbd>C</kbd> and run again will do the trick 😉👌

**Comment by LsHallo** [comment]
In your config.json located in %appdata%\f1viewer (windows) or ~/.config/f1viewer (linux) there is the line
`"live_retry_timeout": 60,`
You can configure this line but f1viewer will check for a live session every 60s with the default config.
You can also see on the right in the log when the check happens. Maybe you disabled the check?

**Comment by balexandre** [comment]
missed that! 🤦‍♂️

please close the issue 😊✌

**Comment by LsHallo** [comment]
You have the power to close the issue right next to the comment button.
