### ISSUE TITLE
MacOS login credentials not saved

### ISSUE THREAD

**Issue by dwerg85** [SoMuchForSubtlety/f1viewer#57]
f1viewer will not safe login credentials in de MacOS keychain. 
After selecting save it'll log in, and then give a 'No keyring configured' message.
I'm running MacOS catalina on both machines I'm having this issue on.

**Comment by SoMuchForSubtlety** [comment]
I'll look into it again.

**Comment by chrisvaughn** [comment]
@SoMuchForSubtlety I'm also experiencing the same problem on Catalina.
installed via Homebrew
```
$ f1viewer --version
Version:     1.1.0
Git commit:  b6963937df1c3608c3bbf0cbc09cf28123893564
Built:       2020-06-29T15:29:14Z
```
When I start up the app I see the following entries in the log
```
2020/07/04 15:25:39 [ERROR] Could not access credential store: Specified keyring backend not available
2020/07/04 15:25:39 [ERROR] No keyring configured
```

 I've done a little digging and I found it works as expected if I run the master branch with `go run ./...` then I get prompted for permission to access the keychain as I would expect. I never see any prompting running the released version.
<img width="449" alt="f1viewer" src="https://user-images.githubusercontent.com/147524/86520479-6d3ebd00-be0a-11ea-8062-cf519c8315f8.png">

I'm not really sure where else to take this debugging but if I can be of any help in testing or collecting info for you please let me know.

**Comment by yannpub** [comment]
I downloaded the binary v1.1.0,  (Version:     1.1.0
Git commit:  b6963937df1c3608c3bbf0cbc09cf28123893564
Built:       2020-06-29T15:29:14Z
)
and I also get the same error :

> 2020/07/08 10:24:09 [ERROR] Could not access credential store: Specified keyring backend not available
> 2020/07/08 10:24:09 [ERROR] No keyring configured

OS: MacOS 10.15.5

Whether in user or sudo mode, I couldn't get the permission pop-up either.

**Comment by SoMuchForSubtlety** [comment]
I found the issue. To access the macOS keychain cgo is needed to call the keychain services API.
Turns out the tool I use to release f1viewer doesn't support cgo.
For future releases I will do macOS builds and homebrew releases manually to circumvent this.

**Comment by SoMuchForSubtlety** [comment]
If you install [1.2.0](https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v1.2.0) this should be fixed
