### ISSUE TITLE
[NEW FEATURE] Be able to specify the max resolution for not-so-fast connections

### ISSUE THREAD

**Issue by balexandre** [SoMuchForSubtlety/f1viewer#58]
from a [Redit user](https://www.reddit.com/user/raf7244)

> The app works great, but is there an option to change stream resolution? My internet connection can't sustain three 1080p streams, and I don't need full resolution for all the streams anyway.

_[original message](https://www.reddit.com/r/F1TV/comments/hkjwkp/you_guys_need_to_try_f1_viewer/fwtqk4h/)_

**Comment by TheDevFreak** [comment]
You could use custom commands combining streamlink and mpv to set the quality - similar to this:

```
	{
		"title": "Stream with Streamlink+MPV",
		"command": ["streamlink", "--player", "C:\\mpv\\mpv.exe", "--hls-audio-select", "*", "$url", "720p"]
	}
```

Your paths to streamlink and mpv may differ (or streamlink may not even be installed)

**Comment by balexandre** [comment]
using 

```json
{
    "title": "Stream 720p",
    "command": ["mpv", "--ytdl-format='bestvideo[height<=720]+bestaudio/best'", "$url"]
}
```

[I can't make it with only MPV player](https://github.com/mpv-player/mpv/issues/4241#issuecomment-653678924)

but I can using VLC preferences pane

![](https://i.imgur.com/z9zQH6D.png)

and the next time it opens VLC, it will run at 720p

as well with 

```json
{
    "title": "Stream 720p",
    "command": ["C:\\Program Files\\VideoLAN\\VLC\\vlc.exe", "--preferred-resolution=720", "$url"]
}
```

only issue with VLC is that after 5 sec in 720p, restarts in 1080p automatically 🤦‍♂️

**Comment by SoMuchForSubtlety** [comment]
As other have said the easiest option if probably to use [the hotkeys](https://mpv.io/manual/master/#keyboard-control) to cycle though video tracks.

I can check the master.m3u8 with ffprobe for available resolutions and then ask the user to select one, but then the user would need ffprobe and I'm not sure that there is an easy way to tell mpv what video track to play.

**Comment by SoMuchForSubtlety** [comment]
This seems to be the requested setting https://github.com/mpv-player/mpv/issues/4241#issuecomment-653799872

**Comment by balexandre** [comment]
for everyone that needs this ... 

the option `--hls-bitrate` is not the width size, as it says, it's the Bitrate you would like ... but there's a better option. When one selects a stream to start with MPV, it will show all available options, like:

```bash
[Downloads]$ mpv https://f1tv-cdn-cent-live.formula1.com/ondemand/399b/_C_/3/2/pit-lane0718044243/1/clip_2_...
│     Video --vid=1 (h264 1920x1080 25.000fps) (7015 kbps)
│     Video --vid=2 (h264 1280x720 25.000fps) (5190 kbps)
│     Video --vid=3 (h264 1024x576 25.000fps) (2963 kbps)
│     Video --vid=4 (h264 768x432 25.000fps) (1953 kbps)
│     Video --vid=5 (h264 640x360 25.000fps) (1310 kbps)
│     Video --vid=6 (h264 512x288 25.000fps) (918 kbps)
│     Video --vid=7 (h264 384x216 25.000fps) (519 kbps)
│     Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
│     Audio --aid=2 (aac 2ch 44100Hz)
│     Audio --aid=3 (aac 2ch 44100Hz) (192 kbps)
```

so all you need to have is a config like:

```json
"custom_playback_options": [ 
  { 
    "title": "Stream on MPV 720p", 
    "command": ["mpv", "--vid=2", "--quiet", "--no-border", "$url"]
  }
]
```

and that would start `--vid=2 (h264 1280x720 25.000fps) (5190 kbps)` automatically

or use any other option for your needs

**Comment by SoMuchForSubtlety** [comment]
thanks! I created a [wiki ](https://github.com/SoMuchForSubtlety/f1viewer/wiki/Tips-and-Tricks#changing-resolution--bitrate-in-mpv)and added this info to it.

**Comment by Max-Enrik** [comment]
@balexandre Looks like you found a solution and thank you that you share it here. I'd like to ask is there a chance to write it in mpv.conf file?
I also tried this `--ytdl-format="bestvideo[ext=mp4][height<=?1080]+bestaudio"`, this doesn't make any changes at all. Thank you!

**Comment by balexandre** [comment]
@Max-Enrik I ended up using the multi command for what I wanted and never looked back ...

I posted my example on [Reddit](https://www.reddit.com/r/F1TV/comments/i1o2ba/guys_ive_created_an_f1viewer_tutorial_its_my/g06xeba?utm_source=share&utm_medium=web2x), but here's the content of it:

```javascript
"multi_commands": [{
  "title": "Onboard, track and data (3440x1440)",
  "targets": [
    {
      "match_title": "Main Feed",
      "command": ["mpv", "--start=0", "--quiet", "--no-border", "--autofit=1750", "--geometry=0:0", "$url"]
    }, {
      "match_title": "Lewis Hamilton",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=1750:0", "--autofit=860", "$url"]
    }, {
      "match_title": "Daniel Ricciardo",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=2600:0", "--autofit=860", "$url"]
    }, {
      "match_title": "Charles Leclerc",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=1750:485", "--autofit=860", "$url"]
    }, {
      "match_title": "Sebastian Vettel",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=2600:485", "--autofit=860", "$url"]
    }, {
      "match_title": "Max Verstappen",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=1750:960", "--autofit=860", "$url"]
    }, {
      "match_title": "Lando Norris",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=2600:960", "--autofit=860", "$url"]
    }, {
      "match_title": "Driver Tracker",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=0:945", "--autofit=860", "$url"]
    }, {
      "match_title": "Data Channel",
      "command": ["mpv", "--aid=no", "--vid=4", "--start=0", "--quiet", "--no-border", "--cache-pause-initial=yes", "--cache-pause-wait=35", "--geometry=687:922", "--autofit=1064", "$url"]
    }
]}
```

and will make my screen show the feeds like:

![](https://i.imgur.com/amnWw7M.jpg)

**Comment by Max-Enrik** [comment]
@balexandre Thank you this is another level.
