### ISSUE TITLE
[NEW FEATURE] Allow Refreshing content list

### ISSUE THREAD

**Issue by TheDevFreak** [SoMuchForSubtlety/f1viewer#59]
After expanding Race Weekends -> 2020 -> Chosen Race  there doesn't seem to be a way to refresh the content within if something new is added while the program is open (such as a paddock pass being added)

**Comment by SoMuchForSubtlety** [comment]
Implemented in https://github.com/SoMuchForSubtlety/f1viewer/pull/86

If you have an event selected and press 'R', the event will be refreshed.
