### ISSUE TITLE
Error to login

### ISSUE THREAD

**Issue by lodiped** [SoMuchForSubtlety/f1viewer#60]
When trying to log in with any account it shows this:

`ERROR: could not log in: got status 401 Unauthorized with {"ContextId":"0d78d642-2b52-43b0-985f-8b9c749c6e72","Code"`

each time I try to log in a new ContextId number appears

**Comment by jfoster** [comment]
Are you using a VPN? If so, disable it as F1TV seems to block logins while a VPN is active.

**Comment by lodiped** [comment]
nope. Not using a VPN.

**Comment by SoMuchForSubtlety** [comment]
So you have an F1TV account and when you try to log in with that email and password you get the error?
What country are you from?

**Comment by lodiped** [comment]
Brazil

**Comment by Hanswurst02** [comment]
Like I wrote in the other post, I had the same Issue.
I think it was on the F1TV side. When I gave my password to a friend it didn't work also. Form him it worked.
A few hours later it worked for me.

**Comment by SoMuchForSubtlety** [comment]
I will close this for now. Feel free to reopen if you have these issues again.

**Comment by ab0mbs** [comment]
@SoMuchForSubtlety, I am experiencing this same issue with the following error code. I've tried over the past few days to get it to work. Any suggestions? I am from the US.

`ERROR: could not log in: got status 401 Unauthorized with {"ContextId":"734fd257-dfa0-4be1-8108-477b3ed4d081","Code"`

**Comment by SoMuchForSubtlety** [comment]
@ab0mbs @lodiped @Hanswurst02 can you please try to run this in your command prompt. Don't forget to set the correct email and password first.
`curl "https://api.formula1.com/v2/account/subscriber/authenticate/by-password" -H "Content-Type: application/json" -H "apiKey: fCUCjWrKPu9ylJwRAv8BpGLEgiAuThx7" --data-raw "{""Login"":""your@email.here"", ""Password"": ""your password here"", ""DistributionChannel"": ""d861e38f-05ea-4063-8776-a7e2b6d885a4""}"`

The result should loom like this 
```
{"SessionId":"[long string of characters]","PasswordIsTemporary":false,"Subscriber":{"FirstName":"your","LastName":"name","HomeCountry":"XXX","Id":123123,"Email":"your@mail.com","Login":"your@mail.com"},"Country":"XXX","data":{"subscriptionStatus":"your status","subscriptionToken":"[another long string of characters]}}
```
Do **NOT** post the result here, it contains sensitive information. Just let me know if the output is as expected.

If that worked as expected try again this time with this command
`curl "https://api.formula1.com/v2/account/subscriber/authenticate/by-password" -H "Content-Type: application/json" -H "apiKey: fCUCjWrKPu9ylJwRAv8BpGLEgiAuThx7" --data-raw "{""Login"":""your@email.here"", ""Password"": ""your password here""}"`

This should also work.

These commands are for windows, if you're using macOS or linux let me know.

**Comment by ab0mbs** [comment]
@SoMuchForSubtlety Both of those commands worked as expected and returned the expected block of JSON

**Comment by ab0mbs** [comment]
@SoMuchForSubtlety I think you can mark this solved for me. I use a password manager and was trying to paste the password in and for some reason, it's cut short when pasting in. Typing it in manually worked fine and logged in successfully. Sorry for the confusion and extra work. Thank you for looking into this!

**Comment by SoMuchForSubtlety** [comment]
No worries!

**Comment by lodiped** [comment]
I think it worked. I tried logging in without the email, just the username and it was giving me that error. Now I tried one of my accounts with the full email and it failed once and worked once. So I don't know if it's the cause or whatever it is but it seems to work... sometimes...

**Comment by lodiped** [comment]
Ok nevermind even when it works and I log in it just ends up with

`ERROR: got status 400 Bad Request with body: {"skylark_error_code": null, "form_validation_errors": nul`

**Comment by woochi1** [comment]
I have same problem with 401 authorized? can anyone help
