### ISSUE TITLE
Is it possible to sync multiple streams?

### ISSUE THREAD

**Issue by Ashiataka** [SoMuchForSubtlety/f1viewer#61]
It would be nice if the video streams could be synced automatically for live sessions. I've tried playing around with custom cache sizes but that doesn't seem to work. Do you think there's a way this can be done programside?

Thanks.

**Comment by SoMuchForSubtlety** [comment]
No, I can't do anything about that, sorry

**Comment by ceesvanegmond** [comment]
This would be an awesome feature though

**Comment by ceesvanegmond** [comment]
How do people do this anyway? When I open a few streams from within f1viewer, the're all off and not in sync at all. Even in live sessions.  @SoMuchForSubtlety

**Comment by anothermindbomb** [comment]
Manually.

**Comment by Ashiataka** [comment]
> Manually.

Yes, it's a complete pain when you've got 6 or 7 streams open at the same time. Because there's no timecode you can't sync that, so you have to guess. I did think that you could do some audio analysis and match up audio and sync it that way, but the onboards don't use the same audio stream so they wouldn't be able to be done that way.

**Comment by ceesvanegmond** [comment]
@Ashiataka there must be a way right?

**Comment by PeteSeta** [comment]
In practice sessions, main feed and data channels can be synced via the session timer.
In the race, the data channels can be synced via flags or lining up the track map (or the little thing in the bottom of the data channel)
