### ISSUE TITLE
Error 401 Unauthorized 

### ISSUE THREAD

**Issue by RiffleMan** [SoMuchForSubtlety/f1viewer#62]
I have problem with logging in. What login and password should I enter in the app to log in?

**Comment by SoMuchForSubtlety** [comment]
Log in using your F1TV email and password.

**Comment by Hanswurst02** [comment]
I have the same problem. 
VPN is disabled.

**Comment by SoMuchForSubtlety** [comment]
dupe of #60 
I will try to help there
