### ISSUE TITLE
[BUG] No live session found

### ISSUE THREAD

**Issue by jannesep** [SoMuchForSubtlety/f1viewer#63]
The app does not find a live session altough one is in progress.

**To Reproduce**
1. Open app
2. App logs in automatically
3. No live session found

**Expected behaviour**
It should show the live session in progress.

**F1TV account plan**
F1TV Pro

**Desktop**
 - Windows
 - Download the zip package and extract
 - Version 1.1.0

**Comment by SoMuchForSubtlety** [comment]
This can happen if the F1TV API is overloaded. I will try to reproduce the issue tomorrow during the race and see if I can find a solution.

**Comment by jannesep** [comment]
At the same time the web UI was working as usual, no signs of overload there at least. Today also the same happened with the F3 and now the F2 sprint race as well.

**Comment by SoMuchForSubtlety** [comment]
Was this persistent during the whole events for you? For me both events showed up.

**Comment by jannesep** [comment]
Yeah, restarted it a few times and then left it running in the background. It did refresh every 60 seconds as per the config but everytime it was "live session not found". My account should be fine since I can extract the stream url from the web ui and play it in VLC for example without any problems.
![kuva](https://user-images.githubusercontent.com/1532070/86530364-e26cc980-bec0-11ea-957c-33036dbec9fb.png)

**Comment by SoMuchForSubtlety** [comment]
I will investigate further. The web UI may use a different method to detect live sessions.

Meanwhile, you can navigate into `Full Race Weekends` and select the live event there.

**Comment by SoMuchForSubtlety** [comment]
@jannesep these are the sessions for this weekend. https://f1tv.formula1.com/api/event-occurrence/even_ff001a6943c14ae794c08592ebd1055d/?fields_to_expand=sessionoccurrence_urls

Sessions are detected as live if the status field for it is set to "live". Right now they are all "upcoming". Please check during the next live sessions if the status is set correctly.

**Comment by SoMuchForSubtlety** [comment]
@jannesep did you have time to test this?

**Comment by jannesep** [comment]
Sorry, forgot to post here yesterday. It still showed me `No live session found` when there certainly was a live session in progress. Your suggested workaround of navigating into `Full Race Weekends` worked fine though.

**Comment by SoMuchForSubtlety** [comment]
I'm interested in what this page says for you when you load it. https://f1tv.formula1.com/api/event-occurrence/even_ff001a6943c14ae794c08592ebd1055d/?fields_to_expand=sessionoccurrence_urls

Can you load it during a live session and post the content here?

**Comment by jannesep** [comment]
F2 Sprint race is currently live. As I took a closer look at the JSON, I found this which would explain why it doesn't find a live session. The workaround still works fine.

![kuva](https://user-images.githubusercontent.com/1532070/87871533-9a1dd300-c9b9-11ea-9907-b7a72893c1ac.png)

**Comment by SoMuchForSubtlety** [comment]
Thanks that helps. The status says "live" so f1viewer should detect it, I'll investigate some more.

**Comment by SoMuchForSubtlety** [comment]
Okay the issue is you're probably in a country without F1TV pro so https://f1tv.formula1.com/api/sets/?slug=grand-prix-weekend-live returns nothing. I use this to determine the current event.

To start a stream you would need a VPN anyway so if you use one the live event should be detected.

**Comment by jannesep** [comment]
Yes, I'm in a country where there's no F1TV Pro. But I'm in EU, so I can still watch without a VPN. Quote from the F1TV FAQ: `If you live in the EU – or a country where the EU Portability Regulation (Regulation EU 2017/2018) – you can access your subscription in any country where the regulation applies.`

But I can manage well enough with the workaround of navigating through the `Full Seasons` etc. Maybe that could be documented somewhere if it's not already?

**Comment by SoMuchForSubtlety** [comment]
Good to know, thanks. I may be able to find an alternative way to detect live sessions.
