### ISSUE TITLE
Cannot play a stream

### ISSUE THREAD

**Issue by ShkiperrrLord** [SoMuchForSubtlety/f1viewer#65]
My F1TV account has F1TV access but I still can't play the stream. It shows me: 
![erroe](https://user-images.githubusercontent.com/55053108/86529837-a0da1f80-bebc-11ea-9be2-e08a70623896.PNG)

**Comment by SoMuchForSubtlety** [comment]
F1TV access is only for replays. You need F1TV pro for live streams. You can read the details here https://www.formula1.com/en/subscribe-to-f1-tv.html
