### ISSUE TITLE
[BUG] Can't scroll down in the viewer

### ISSUE THREAD

**Issue by Aderranyth** [SoMuchForSubtlety/f1viewer#67]
I can use the enter key to log in but can't scroll down nor save my log in.

**Comment by dwerg85** [comment]
Which OS are you running? 
Did you try scrolling using your arrow keys? That's how it works.

**Comment by gumialex** [comment]
> I can use the enter key to log in but can't scroll down nor save my log in.

I have exactly the same problem! Probably it's a windows related bug though...

**Comment by Aderranyth** [comment]
> 
> 
> Which OS are you running?
> Did you try scrolling using your arrow keys? That's how it works.

Windows. Yeah I'm using the arrow keys.

**Comment by SoMuchForSubtlety** [comment]
You have to use the tab key to navigate to the save button. Then you can save the login credentials.
