### ISSUE TITLE
[Feature] can you please add to Chocolatey repo?

### ISSUE THREAD

**Issue by balexandre** [SoMuchForSubtlety/f1viewer#69]
Would be amazing if we could install through [Chocolatey](https://chocolatey.org/search?q=f1viewer) so it not only installs `f1viewer` but also MPV player making it even  easier for us to update every time there's a new version 😊👌

**Comment by SoMuchForSubtlety** [comment]
I created a package. It should show up 'within 1-3 business days' unless it gets rejected.

**Comment by SoMuchForSubtlety** [comment]
https://chocolatey.org/packages/f1viewer/

**Comment by balexandre** [comment]
I've been checking this every day ... they '1-3 business days' are like Microsoft time 😁

but I was wondering if it wouldn't be better to close only when the package is live and available to work, and from that, add it to the readme file so everyone knows?

just afraid, that by closing the issue, will be forgotten 😢

**Comment by SoMuchForSubtlety** [comment]
I added it to the readme, don't worry I won't forget :)

**Comment by SoMuchForSubtlety** [comment]
`Failed to process request. 'The package f1viewer has a previous version in a submitted state, and no approved stable releases. Please work to have the existing package version approved or rejected first.'.
The remote server returned an error: (403) Forbidden..`

Looks like even more waiting for 1.2.0 🙂
