### ISSUE TITLE
[Feature] have a Logout menu to clear credentials

### ISSUE THREAD

**Issue by balexandre** [SoMuchForSubtlety/f1viewer#70]
We might just try in a friend computer as we're passing the afternoon there, but it's a bit hard to actually clear our credentials so the next time we run `f1viewer` it will ask for the account info once again...

Maybe add a menu option for this?

**Comment by SoMuchForSubtlety** [comment]
closed by 5f5a57053d83eed653911a9d0d1a933eebb6df79, thanks @chrisvaughn
