### ISSUE TITLE
[BUG] all subtitles mashed together

### ISSUE THREAD

**Issue by ikt** [SoMuchForSubtlety/f1viewer#81]
**Describe the bug**
As per subject, not sure if this is an mpv bug but I have 8 audio channels selectable but only 1 closed caption/subtitles selectable and that 1 option appears to be mixing all the subtitles for all languages together

Not much to show, I assume when you turn closed caption on it only shows the language you want.

https://imgur.com/Bf4QgJ2

**F1TV account plan**
pro

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - deb
 - Version:     1.1.0
Git commit:  b6963937df1c3608c3bbf0cbc09cf28123893564
Built:       2020-06-29T15:28:49Z

**Comment by SoMuchForSubtlety** [comment]
Yea that looks like an mpv issue, but I'll double check during the next live session.

**Comment by SoMuchForSubtlety** [comment]
It's an mpv / ffmpeg issue, I can't do anything about it.
