### ISSUE TITLE
[FEATURE] Custom command for AlwaysOnTop

### ISSUE THREAD

**Issue by clampy** [SoMuchForSubtlety/f1viewer#85]
**Is your feature request related to a problem? Please describe.**
Being able to 'fullscreen' multiple windows, while keeping taskbar settings the same (no auto-hide), for pure ease of use.

**Describe the solution you'd like**
Add a custom command which will flag the window as AlwaysOnTop

**Describe alternatives you've considered**
Hiding taskbar. Using other programs like OBS to arrange and 'fullscreen' the preview. These alternatives would just be slower when setup is done.

**Additional context**
Nothing extra required.

Thank you.

**Comment by SoMuchForSubtlety** [comment]
I think this is out of scope for f1viewer.

You can enable it in mpv if you create a custom command with the flag `--ontop` as described here https://github.com/mpv-player/mpv/issues/2492

For VLC you can enable the setting [like this](https://www.vlchelp.com/always-on-top/).

**Comment by clampy** [comment]
Thank you, sorry for wasting your time :)
