### ISSUE TITLE
[BUG] Can't upgrade to 1.2.0 via brew

### ISSUE THREAD

**Issue by slhodson969** [SoMuchForSubtlety/f1viewer#87]
**Describe the bug**
I successfully installed 1.1.0 last night. This morning I see there is an update available but I am unable to update. I keep getting the following errors:

```
brew upgrade SoMuchForSubtlety/tap/f1viewer
==> Upgrading 1 outdated package:
somuchforsubtlety/tap/f1viewer 1.1.0 -> 1.2.0
==> Upgrading somuchforsubtlety/tap/f1viewer 1.1.0 -> 1.2.0 
Error: could not get runtime dependencies from /usr/local/Homebrew/Library/Taps/somuchforsubtlety/homebrew-tap/Formula/f1viewer.rb!
Error: No available formula with the name "vlc" (dependency of somuchforsubtlety/tap/f1viewer)
```

**To Reproduce**
1. Run `brew upgrade SoMuchForSubtlety/tap/f1viewer`
2. See error

**Expected behaviour**
It should update to version 1.2.0
**F1TV account plan**
I have pro but this is before you even start the app

**Desktop (please complete the following information):**
 - macOS
 - Brew
 - Version:

```
Version:     1.1.0
Git commit:  b6963937df1c3608c3bbf0cbc09cf28123893564
Built:       2020-06-29T15:29:14Z
```

I'm guessing the issue has something to do with VLC not being installed, but shouldn't it take care of installing its own dependencies?

**Comment by SoMuchForSubtlety** [comment]
Thanks for catching that, I updated the formula. Please let me know if it works

**Comment by slhodson969** [comment]
Yes, it works now. Thanks for the super fast response and also for this great tool!

I also love that it is now able to save my credentials so I don't have to type them in each time ❤️
