### ISSUE TITLE
[FEATURE] proxy requests

### ISSUE THREAD

**Issue by HughRaynor** [SoMuchForSubtlety/f1viewer#88]
**Is your feature request related to a problem? Please describe.**
I receive 400 errors when attempting to load a stream without a proxy / VPN configured.

**Describe the solution you'd like**
Please look to implement an option to connect via (authenticated) proxy server.

**Describe alternatives you've considered**
Using a global VPN profile, however this impacts all traffic, not just F1TV.

**Additional context**

**Comment by Sgtpanda** [comment]
I also came here to ask for this. From what I gathered from looking at GoLark, the best way to do it (I think) would be to create a HTTP client with a custom transport and pass that to the `withClient` function of GoLark. I may have a go at trying this myself but no promises as I have zero experience with Go.

**Comment by Sgtpanda** [comment]
So I found out it's actually even simpler than that, Go will use the HTTP_PROXY environment variable, and so will MPV, so all you need to do is set that environment variable in your terminal before you launch and it will work perfectly fine.

If you wanted to make this part of f1viewer you could simply add a config option and use `os.Setenv("HTTP_PROXY","<CONFIG_URL>")`.

The only problem is VLC doesn't read this environment variable and needs to be configured manually I think, maybe a command line option would be available?

**Comment by callumparr** [comment]
Am using a VPN (Ivacy software) to circumvent the geolock of F1TV. I didnt quite get the url for the proxy. Is there a way to configure environment on macOS terminal? I noticed that I can easily stream from F1TV website with VPN but if going through the f1viewer the live streams just won't buffer but work ok with old sessions. Is it just a demand thing?

**Comment by SoMuchForSubtlety** [comment]
@Sgtpanda yea I think that is the best approach. I don't really want to integrate a proxy directly into f1viewer since I don't want to openly flaunt the country restrictions.
