### ISSUE TITLE
[BUG] VLC Playback error V1.2.0

### ISSUE THREAD

**Issue by 13AscensioN** [SoMuchForSubtlety/f1viewer#89]
When choosing to play with VLC a continuous error appears on the right side stating "main libvlc error: stale plugins cache:". I'm assuming there's more after that but that's where the window cuts off. VLC does open and sometimes audio begins to play for a little bit but no video nor continuous playback.

The usual way to start any video/stream.

Expected behaviour:
Normal playback of selected item.

Screenshots:
![f1viewervlc](https://user-images.githubusercontent.com/8076140/87879047-7920a680-c9e8-11ea-8728-af7167208444.PNG)

F1TV account plan:
F1 TV Pro

Desktop (please complete the following information):
 - Windows 10 Version 1909 (OS Build: 18363.959)
 - Manually placing f1viewer in VLC installation folder
 - V1.2.0 (Latest)

Logs:
Logs provide nothing extra.
2020/07/19 17:43:25 [INFO] logged in!
2020/07/19 17:43:25 [INFO] checking for live session
2020/07/19 17:43:25 [INFO] could not find mpv
2020/07/19 17:43:29 [INFO] no live session found

**Comment by SoMuchForSubtlety** [comment]
Yea VLC is still hit or miss, I can't do anything about it. It works for some streams, for the other ones you will need to use mpv

**Comment by 13AscensioN** [comment]
Alright thank you. If it can be of any help: using streamlink (so long as you have the link beforehand) you can flawlessly play any stream/video from F1TV in VLC. That's how I did it before it became a feature in V1.2.0. I open f1viewer and copy the link and than use streamlink to start playing it in VLC. I just prefer VLC cause I'm familiar with it and it has support for chromecast. It doesn't allow for scrolling back and fast forwarding though as far as I'm aware. Perhaps it could be worked into f1viewer like this?

**Comment by 13AscensioN** [comment]
VLC update 3.0.11 improves HLS support and seems to fix this issue so this ticket can be closed.
