### ISSUE TITLE
403 Issues

### ISSUE THREAD

**Issue by clearview1** [SoMuchForSubtlety/F1viewer#9]
Do I add my cookie/login credentials somewhere, or how this works?

**Comment by SoMuchForSubtlety** [comment]
You don't need credentials, what issues do you have?

**Comment by clearview1** [comment]
I just had alot of Permission issues, seems to be workning now after a restart 👍 A quick question, whats the best for converting the m3u8 to a mp4? Cheers!

**Comment by SoMuchForSubtlety** [comment]
Take a look at ffmpeg, it should do it without a problem. There are tons of tutorials and documentation.
