### ISSUE TITLE
Remember to update Chocolatey package

### ISSUE THREAD

**Issue by balexandre** [SoMuchForSubtlety/f1viewer#91]
it's currently installing 1.1.0

https://chocolatey.org/packages/f1viewer

**Comment by SoMuchForSubtlety** [comment]
thanks, I'll update when I'm home again in Wednesday.

**Comment by balexandre** [comment]
made a [little tutorial](https://youtu.be/Bps1nIvGa5o) and shared on [Reddit](https://www.reddit.com/r/F1TV/comments/i1o2ba/guys_ive_created_an_f1viewer_tutorial_its_my/?utm_source=share&utm_medium=web2x), if you want to add to the `readme`, fell free... couldn't show how easy is to install via chocolatey though 😢 maybe when you update it 😁

**Comment by SoMuchForSubtlety** [comment]
https://chocolatey.org/packages/f1viewer/1.2.0

**Comment by balexandre** [comment]
just a friendly reminder to update [Choco](https://chocolatey.org/packages/f1viewer/) to 1.4.0 😊
