### ISSUE TITLE
youtube-dl failed: not found or not enough permissions

### ISSUE THREAD

**Issue by springcomp** [SoMuchForSubtlety/f1viewer#96]
**Describe the bug**

Even though I can watch live sessions from the browser, the app says I do not have enough permissions.
I can still watch archive footage.

**To Reproduce**

- Launch f1viewer
- Wait for the 'logged in' message.
- Choose a live session, drop down to `Main Feed` and then `Play with MPV`.

**Expected behaviour**

An MPV window should open with the feed.

**Screenshots**

![image](https://user-images.githubusercontent.com/8488398/89732309-23bb4080-da4e-11ea-9a64-abef498598fe.png)

**F1TV account plan**

F1TVPro

**Desktop (please complete the following information):**
 - OS : Windows 10 - 2004 (19041.388).
 - installation method : download from GitHub releases.
 - Version  1.2.0.
- Commit e2959e06353d1c215e1bf6078dbc8d0082657148.
- Built:       2020-07-19T09:32:37Z.

**Logs**

```
2020/08/09 14:43:48 [INFO] logged in!
2020/08/09 14:43:48 [INFO] checking for live session
2020/08/09 14:43:48 [INFO] could not find vlc
[~]$ mpv https://f1tv-cdn-cent-live.formula1.com/live/wif0│
 tls: handshake failed: error:14FFF3E7:SSL routines:(UNKNO│
Failed to open https://f1tv-cdn-cent-live.formula1.com/liv│
[ytdl_hook]                                               │
[ytdl_hook] youtube-dl failed: not found or not enough per│
                                                          │
                                                          │
Exiting... (Errors when loading file)
```

**Comment by SoMuchForSubtlety** [comment]
What version of MPV are you using? Make sure it's the latest version from here https://sourceforge.net/projects/mpv-player-windows/files/

**Comment by springcomp** [comment]
I was using this version:
https://github.com/mpv-player/mpv
Which seemed more authoritative.
Will test next Grand Prix.

**Comment by balexandre** [comment]
@springcomp unfortunately, the latest release of MPV was released in January 

![](https://i.imgur.com/gJlnMNB.png)

and does no implement the latest fixes they did to fix the **TLS Handshakes**

by installing a newer version from the GitHub source code, you will be able to make it work without much hassle, compile your own or use SoundForge versions, remember to uninstall the "official stage" version first

Check the latest [SoundForge installation files](https://sourceforge.net/projects/mpv-player-windows/) that are up-to-date periodically with source code

**Comment by springcomp** [comment]
@balexandre this sounds totally correct, I would never have thought about this.
Maybe I should try this and then make a little pull request to clarify the docs 😂

**Comment by xAndrettix** [comment]
I can appreciate all the work you've put into this and have really enjoyed being able to use it.  That being said, I am having the same issue as mentioned above, but I have no idea how to uninstall the 'official stable version first' to then install the newer version to get this back to working.  MPV is not listed anywhere in 'uninstall or change a program' either.

OS Windows 10 2004
Build: 19041.572

Suggestions or help would be appreciated.  Getting this to work previously was only an option for me since I was able to follow your video to get it all working step by step.  Fixing this seems to be sort of the same situation for me, but if you could point me in the right direction, hopefully that would help.

Thank you

**Comment by balexandre** [comment]
Hi @xAndrettix 

You have several ways ... 

`MPV` is just an application (executable and dll's) and they are always in the same place, and if you open powershell and write `mpv` and press Enter, you will probably have something like

![](https://i.imgur.com/oXwsbVs.png)

as you can type `mpv` that means it's set as an environment variable and all you need is to check that path

![](https://i.imgur.com/dc9NejT.png)

and then check what path points to `mpv`

![](https://i.imgur.com/PyKCubD.png)

in my case, it points to `C:\ProgramData\chocolatey\lib\mpv.install\tools` so I can use [chocolatey](https://chocolatey.org/) to uninstall it or remove that entry and point to a new folder where the new mpv version is ... 

save and press OK
