### ISSUE TITLE
[BUG] MPV or VLC not detected

### ISSUE THREAD

**Issue by diegolrz** [SoMuchForSubtlety/f1viewer#97]
**Describe the bug**
I have both MPV and VLC installed but F1viewer is not detecting either one.

**F1TV account plan**
Do you have a free, access or pro account? Pro account

**Desktop (please complete the following information):**
 - OS Windows 10 64bit
 - installation method downloaded the exe from github
 - Version [`f1viewer -v` output] 1.2.0
 - VLC Version 3.0.11 win64

**Logs**
Please provide the relevant portion of your logs. On Windows you can find them under `%appdata%\f1viewer\logs`, on macOs in `$HOME/Library/Application Support/f1viewer/logs` and on linux in `$HOME/.local/share/f1viewer/`

2020/08/09 08:00:17 [INFO] logged in!
2020/08/09 08:00:17 [INFO] checking for live session
2020/08/09 08:00:17 [INFO] could not find vlc
2020/08/09 08:00:17 [INFO] could not find mpv
2020/08/09 08:00:17 [ERROR] Both MPV and VLC are unavailable!

**Comment by SoMuchForSubtlety** [comment]
VPC and MPV need to be in your PATH. [Here](https://www.vlchelp.com/add-vlc-command-prompt-windows/  )are instructions for VLC (the "Making VLC Work from Anywhere in the Command Prompt" section). Do the same for MPV.

**Comment by diegolrz** [comment]
That did it! That would be a great addition to the Readme.
