### ISSUE TITLE
[FEATURE] Verbose refresh

### ISSUE THREAD

**Issue by dwerg85** [SoMuchForSubtlety/f1viewer#98]
Could the refresh function be made verbose? At the moment the user knows they pressed the button but has no idea if nothing is happening because the app didn't refresh or because nothing is coming up. 

**Describe the solution you'd like**
A message that mentions that the app is refreshing.

**Comment by SoMuchForSubtlety** [comment]
What do you mean by refreshing? Refreshing an event by pressing `r`? It only works if the even you want to refresh is selected like this ![image](https://user-images.githubusercontent.com/15961647/89733031-02a91e80-da53-11ea-93a2-4aa2c81b7e7f.png) then it shows the `loading...` animation if you press `r` ![image](https://user-images.githubusercontent.com/15961647/89733068-3edc7f00-da53-11ea-8eed-fae488d0ec58.png)

**Comment by dwerg85** [comment]
Then I guess the problem was on my end. I'll close the issue.
